laravel/cashier-stripe

- src/Laravel/Cashier/Invoice.php
The `$timezone` variable was previously unused.
> added timezone variable for correct date handling

- src/Laravel/Cashier/StripeGateway.php
`createStripeCustomer` returns the result of `getStripeCustomer` and because `getStripeCustomer` returns a `Stripe_Customer` then `createStripeCustomer` does the same.
> Fix docblock to show correct return type.

- src/Laravel/Cashier/Invoice.php
Amended as per #154 
Checking whether an invoice has a discount is inaccurate when an invoice has tax applied as the sub total and total do not match. This will resolve the issue, or a check for if the subtotal + tax equals the total would work too.
> Discount can't be null if it has a discount

- src/Laravel/Cashier/StripeGateway.php
Use the getCurrency function instead of hardcoding usd.
Had a suprise when I tried to charge my clients.
> Use getCurrency instead of usd

- src/Laravel/Cashier/Billable.php
- src/Laravel/Cashier/Contracts/Billable.php
- src/Laravel/Cashier/StripeGateway.php
- tests/BillableTraitTest.php
- tests/StripeGatewayTest.php
A user can now override the `getTaxPercent()` method to provide a
percentage tax to stripe. Implemented as a method so that it can be
calculated on a per-user basis
> Added tax percent method to Billable trait

- src/Laravel/Cashier/Billable.php
- src/Laravel/Cashier/Contracts/Billable.php
- tests/BillableTraitTest.php
Stripe throwns an error when tax_percent is empty ( Invalid decimal: ; must contain at maximum two decimal places ), let's default it to 0.
> Fixing tax_percent issue

- src/Laravel/Cashier/WebhookController.php
I thought this was closer to being a bug that being a feature so I haven't created an issue for this.
When trying to test webhooks through the stripe interface my requests were being blanked because the events don't exist on stripe's end.
I've added a minor change that checks if we are in live mode and continues if we aren't.
> Fixing an issue with not being able to test stripe webhooks

- src/Laravel/Cashier/Invoice.php
I had a permission error that was hidden from me till I did `mustRun`.
The hidden error was `sh: 1: /home/vagrant/Code/sponsor/vendor/laravel/cashier/src/Laravel/Cashier/bin/linux-x86_64/phantomjs: Permission denied`
Now it will throw in error. Prior to this the PDF printed but could not be opened.
> [Proposal] Using mustRun to force exception

- src/Laravel/Cashier/StripeGateway.php
There is no easy way to set a new Quantity on a subscription. Currently the only choices are `increment` and `decrement` - but that assumes you want to only increase/decrease from a previous known amount. 
There are useful times where you just want to set a specific quantity - regardless of any previous number.
Before the pull you could do this:
```
$user->subscription()->updateQuntity($user->subscription()->getStripeCustomer(), 10);
```
Now you can just do
```
$user->subscription()->newQuantity(10);
```
> newQuantity

- src/Laravel/Cashier/StripeGateway.php
- tests/StripeGatewayTest.php
Subscription update provides "Invalid integer" message if 'trial_end' is set to null. Making 'trial_end' optional
> [Bug] Subscription update provides "Invalid integer"

- src/Laravel/Cashier/WebhookController.php
After seeing the pull request #190 I wanted to contribute with what looks to me a better solution.
As @taylorotwell said using environment variables looked like a better choice.
To keep it simple I added a isInTestingMode method that return a boolean according to the CASHIER_TESTING env variable.
Then in the handleWebhook method we can verify that we are not in testing mode.
> Allow testing of Webhooks using ENV

- src/Laravel/Cashier/StripeGateway.php
Added a check to make sure customers are not deleted before proceeding to find an existing subscription. `Customer::usingMultipleSubscriptionApi()` will cause an error as Customer::subscriptions does not exist for deleted models. Deleted customers do not have existing subscriptions so proceeding to find a subscription is not necessary.
The error is Stripe Notice: Undefined property of Laravel\Cashier\Customer instance: subscriptions
> Added deleted check for getStripeCustomer

- src/Laravel/Cashier/EloquentBillableRepository.php
Currently only one model with a billable interface works. This allows the `services.stripe.model` config setting to be either a string with a single model or an array of models.
I know it's rare to use multiple models with Cashier, but I'm working on a project right now where customers can have subscriptions on either individual listings or their account.
> [Proposal] Allow multiple models

- composer.json
Being so strict is unneeded, and a bit silly given we allow usage with laravel 5.3 components which require symfony 3.1's http stuffs.
> Relax symfony version constraint a touch

- src/Subscription.php
Calling incrementAndInvoice without an argument would result in incrementQuantity being called with a null value, which is unexpected behaviour in my mind. Updating incrementAndInvoice to accept a count argument makes it function like the other methods and is thus much more intuitive.
Secondly, this function wasn't actually invoicing the user as one is led to believe by the function name.
> Fix incrementAndInvoice function

- composer.json
Currently the package.json name was changed to "new-cashier".  This doesn't match the packagist name.  From what I could find out, there's not a simple way to update the packagist name.
Because the names don't match up, it makes it not possible to fork the repo and override it in the "repositories" root object.
> Update package name to match packagist existing name

- src/Http/Controllers/WebhookController.php
The logic of the Boolean expression in the previous order makes it so that the event existence is always checked against the Stripe servers first before checking whether this is a test. This results in slower tests as each test will make this round trip even though the condition will make it so the result is irrelevant.
The proposed ordering omits the check against the Stripe servers entirely during tests. This change has no real consequence in terms of effective logic since even if one explicitly wanted it to check that the event exists in Stripe, the `&& !` was making the result irrelevant when testing.
This is the propose PR for #261.
> Change order of boolean test for faster tests

- src/Billable.php
If the developer uses the trait Billable in models with a name different from 'User', the foreign key is set incorrect, already what the pattern is 'user_id'.
> Fix the foreign key for the different models

- src/Cashier.php
Clean up formatAmount() method by removing unnecessary else statement.
> Remove unnecessary else from formatAmount() method.

- src/SubscriptionBuilder.php
You can use this parameter to attach key-value data to the subscriptioin.
```
$user->newSubscription('main', 'monthly')
->withCoupon('code')
->withMetadata(['key' => 'value'])
->create($creditCardToken);
```
> Add metadata to new subscription

- src/Subscription.php
**Moved this onto branch 6.0 as requested**
This is a little update that allows you to set prorate and billing_cycle_anchor when swapping a subscription plan.
Usage is:
$user->subscription()->noProrate()->billingCycleAnchor("now")->swap($stripe_plan);
I proposed this need way back in 2014 on this pull request: #88
It looks like it was implemented elsewhere: #210
But subsequently dropped in Cashier 6.0 (along with noProrate()) unless I'm massively overlooking something.
> Added no prorate and billing cycle anchor setters for subscription swapping.

- src/Billable.php
Since a user can cancel a plan and re-subscribe, this method could return an invalid plan. This fix will only return valid ones (which I think is the desired behavior?).
> onPlan() issue with valid plans

- src/SubscriptionBuilder.php
Coupon must be passed to the stripe API on subscription creation for the withCoupon method to do anything.
This is a pretty big oversight. I don't know if it's worth putting out an email or something. Customers of anyone using withCoupon on signup are not getting their coupons applied.
> Pass coupon to Stripe API when using withCoupon

- src/Billable.php
Allows you to check if the customer currently has a card on file.
This PR adds three methods:
* `public function hasCardOnFile() : bool` **Determines if the user, according to the local DB, has a card linked.**
* `public function syncCustomerCardDetails : $this` **Forces the refresh of the customer's card details from Stripe's API.**
* `protected function fillCardDetails : $this` **Replaces the data about the card in the database for the Billable model.**
> Add hasCardOnFile method to Billable

- resources/views/receipt.blade.php
- src/Invoice.php
- src/InvoiceItem.php
Invoice items now use Carbon for start and end dates in subscriptions (allows formatting and localization)
Invoice date now uses UTC for instantiation since Stripe's API uses UTC for all dates (see https://support.stripe.com/questions/what-timezone-does-the-dashboard-and-api-use)
> Dates improved

- src/Billable.php
In the Cashier documentation, it's mention that a requirement for getting setup for Stripe is to set the model and secret values in services.php. 
Currently when retrieving the Stripe key, Cashier is defaulting to using the getenv() function to retrieve the key instead of the config() function. 
When using the Laravel config cache option:
`php artisan config:cache`
Cashier stops working as the getStripeKey() function returns `false`.
This patch simply uses the config() function in place of the getenv() function, and fixes Cashier for everyone caching their config via Laravel. The solution was mentioned in #243
> Use the config value when retrieving the Stripe key

- composer.json
- src/Invoice.php
Currently Cashier requires `dompdf/dompdf@^0.6.1`. The `dompdf` package has been updated to `0.7` so this now shows as an outdated package when running `composer outdated -D` on a Laravel 5.3 project.
I have updated Cashier to use Dompdf 0.7 and tested the PDF downloads using our Laravel 5.3 application. I have also run PHPUnit on this change which resulted in 0 failures.
```
$ ./vendor/bin/phpunit
PHPUnit 4.8.27 by Sebastian Bergmann and contributors.
..........
Time: 40.91 seconds, Memory: 8.00MB
OK (10 tests, 58 assertions)
```
> [Proposal] Upgrade to Dompdf v0.7

- readme.md
- resources/views/receipt.blade.php
- src/Billable.php
- src/Cashier.php
- src/Invoice.php
- src/InvoiceItem.php
- src/Subscription.php
- src/SubscriptionBuilder.php
This is a pull request related to proposal #334 
I know that guidelines dictate that a proposal needs to be approved, but I think this PR will better explain the goal of the proposal.
One of the main changes other than the dynamic loading of the correct model and foreign key based on the configuration, I renamed a variable related to the model from `user` to `owner` (in lack of a better word).
For backward compatibility, the `Subscription::user` method remains, but utilizes `Subscription::owner`.
Also, updated the README to better match test setup conditions.
> Enabled dynamic loading of Stripe model

- src/Subscription.php
Currently
`$subscription->noProrate()->updateQuantity($amount);` does not correctly set the prorate argument on the Stripe API when updating the subscription.
The proposed change automatically sets the `prorate` property that's on the Subscription model.
> Set Subscription Prorate Argument when using updateQuantity

- src/SubscriptionBuilder.php
Remove coupon attachment to customer when creating a new customer as part of the subscription creation process. Currently, if a new subscription is created for a user who is not already registered with Stripe, then the coupon is applied to both the customer entity AND the subscription. This results in the coupon being applied to payments multiple times. If attaching a coupon to the customer entity is required, the Stripe customer may first be created explicitly calling (Billable model)->createAsStripeCustomer($token, $options), where 'coupon' is set as one of the options .
> Fix coupon being double applied

- src/Subscription.php
As per the docs https://laravel.com/docs/5.3/billing#changing-plans
> If you would like to swap plans and cancel any trial period the user is currently on, you may use the  skipTrial method:
```
$user->subscription('main')
->skipTrial()
->swap('provider-plan-id');
```
However the Subscription model doesn't have a `skipTrial()` method, this PR adds the proper method.
> Fix Skipping trial on swapping

- src/SubscriptionBuilder.php
- tests/CashierTest.php
Allows you to explicitly define when a trial will end.
#345
> Specify trial duration of a subscription with DateTime

- composer.json
This version fixes the PHP 7.1 bug (numeric value encountered). See 
https://github.com/dompdf/dompdf/releases/tag/v0.8.0
> Bump dompdf

- src/Subscription.php
got this when tried to swap plan
`Call to a member function retrieve() on null in /cashier/src/Subscription.php:374`
So, think it is better to handle case, if Stripe customer has no any subscriptions
> Handle exception, if stripe customer has no any subscriptions

- src/Billable.php
Adding full bank account support to cashier is a whole separate story, but these two changes let Cashier work if you pass a bank account token to it or call `updateCardFromStripe()` on a user who has a bank account set as their default payment type (in Stripe).
> Don't break on bank account tokens

- src/Subscription.php
`today` method causes wrong behaviour. If subscription was paid and turned into active, user can't change subscription via `swap` method till the end of day - it causes transmitting `trial_end` from past time. So client gets a message "Invalid timestamp: must be an integer Unix timestamp in the future." out of API call.
> Correct trial

- resources/views/receipt.blade.php
In theory, we could use the existing `$vat` variable, but that's being used/overwritten in `Spark` to supply the information from the client, not the vendor.
This would allow a user to supply a `$vendorVat` variable to be added to the vendor information, below the address.
This would also solve issue #441.
> Allow the vendor VAT to be supplied, as required by EU regulations

- src/Subscription.php
- tests/CashierTest.php
This PR fixes an issue as identified at issue #412.
It allows for a simple way to update the subscription name when swapping a plan.
If the PR is accepted, I will submit a separate PR to update the Laravel Cashier documentation.
> Changing plans does not change the local subscription name (#412)

- composer.json
As said in https://github.com/dompdf/dompdf/issues/1272 the versions of dompdf before 0.8.1 do not work properly with php 7.1
> Dompdf version fixed for php 7.1

- src/Billable.php
Quick bug fix for an issue mentioned in #370 where the user's Stripe card details aren't removed from their model entry on running the `deleteCards()` method.
Fixed by triggering by synchronizing the user's card details with Stripe after card deletion.
> Bug fix for issue mentioned in #370 - Cards not synchronising with table after card deletion.

- .travis.yml
- composer.json
- tests/CashierTest.php
- tests/WebhookControllerTest.php
Updated `phpunit/phpunit` to `~6.0`.
Dropped support to `PHP 5.6`, as PHPUnit 6.0 [requires PHP 7.0](https://github.com/sebastianbergmann/phpunit/blob/master/composer.json#L25).
> [8.0] Updated to PHPUnit 6

- src/Invoice.php
Tax must be added to subtotal to have a correct discount value:
**Without the fix:**
Subtotal = **100$**
Coupon = **50$**
Tax = **10$**
Total = **60$**
`function discount()` = **40$** ⚠️ bad result
**With the fix:**
Subtotal = **100$**
Coupon = **50$**
Tax = **10$**
Total = **60$**
`function discount()` = **50$** 👍 good result
> Add tax to subtotal

- src/Billable.php
Ensures that the `customer_id` (`stripe_id` within cashier) matches the `customer_id` which is returned from the Stripe invoice.
Not checking this poses a security risk in a scenario where `invoice_id`'s are exposed, which the [documentation suggests](https://laravel.com/docs/5.5/billing#invoices).
If you would like a unit test for this let me know. I think the easiest way to test it would be to create a second user and attempt to access an invoice from the first user which will now throw an `AccessDeniedHttpException`.
> [Security] Prevents unauthorized access to Stripe invoices

- src/Subscription.php
Cashier tries to set `billingCycleAnchor` on the Stripe Subscription object. This makes Stripe throw an exception: `Received unknown parameter: billingCycleAnchor`. The correct parameter name is `billing_cycle_anchor`. 
Also see: https://stripe.com/docs/api#update_subscription-billing_cycle_anchor
This bug was introduced by [this commit](https://github.com/laravel/cashier/commit/6fdbd62103a2c7bd3f346a76a2c82387aaba76b2#diff-dde586b4ea0798ea4a467b9eba070a7e).
> Fix anchorBillingCycleOn()

- src/Billable.php
The [`download`](https://github.com/laravel/cashier/blob/master/src/Invoice.php#L274) function on `Laravel\Cashier\Invoice` only accepts one argument: `array $data`
Targeting `master` as this may be a breaking change due to the API changing for the public `downloadInvoice` function, although I guess it isn't *really* breaking as it wouldn't do anything passing it, and it won't break if you continue to pass it 🤷‍♂️ Let me know if another branch is more suitable.
PS: Thank you for creating and maintaining Cashier.
> [Fix] Remove unnecessary storage path variable

- phpunit.xml
- readme.md
It took me a few minutes to work out where to put the test variables [mentioned in the readme](https://github.com/laravel/cashier#env).
I thought having them already setup might be nicer for others in the future. I also thought this might interfere with your testing setup - but perhaps if it does we can just comment them out - but leave them there as a guide for others.
I also removed the `STRIPE_KEY` from the readme as this is not required to run the unit tests.
> [Proposal] Add test variables to phpunit.xml

- src/Subscription.php
- tests/CashierTest.php
I found I was looking for these additional methods on the subscriptions and thought I'd see if they we wanted in the package.
| |Trial|Trial + Cancelled|Recurring|Recurring + Cancelled|Cancelled [ended]|
|-|---- |-----------------|---------|---------------------|-----------------|
|`ended()`|❌|❌|❌|❌|✅|
|`recurring()`|❌|❌|✅|❌|❌|
In an admin area I found `ended` is good to be able to find out how many subscriptions are no longer potentially resumable and `recurring` is useful to show how many users you are going to continue making money from.
> [Proposal] Add ended and recurring helpers

- src/Billable.php
- src/Subscription.php
Carbon offers `isFuture()` and `isPast()` methods that make understanding the logic of date checks much nicer IMO and cleans up these methods to simple, readable one liners.
✅ Tests are passing.
> [7.0] More readable date checks

- src/Subscription.php
Tweaked this method to reuse the already retrieved class - instead of determining it from the "newed" up model and calling `get_class` on it.
✅ Tests are passing.
> [7.0] Reuse existing class variable

- src/Cashier.php
- src/Http/Controllers/WebhookController.php
- src/Subscription.php
The retrieval of the stripe model class is a bit more than a simple config call so it felt nicer in its own method.
Note that at some point these got out of sync (another benefit to making a dedicated method call) and `src/Subscription.php` file has a fallback default `'App\\User'` which will now be in place for web hook call.
Ran the tests against PHP7.2 and all sweet.
> [7.0] Dry up stripe model retrieval

- src/Invoice.php
Cashier requires `"dompdf/dompdf": "^0.8.0"` but includes customisation support that was removed in `0.7.0`.  This can be misleading when customising invoice templates.
It's noted in the docs and by the maintainer in this reference.
https://github.com/dompdf/dompdf/issues/1351
> remove old dompdf custom configuration support

- src/SubscriptionBuilder.php
- tests/CashierTest.php
This allows you to anchor a new subscription to a specific date. For example, this allows you to anchor a new subscription to the 1st day of the next month. This makes the renewal date of the customer become the 1st of the month instead of on the day they initially signed up.
This feature already exists within Cashier for swapping subscriptions, but it wasn't there for new subscriptions. This fixes that.
> Add ability to anchor a new subscription to a billing cycle date.

- src/Subscription.php
Fix subscription cancel method, so it works with stripe api version 2018-08-23
More info here https://stripe.com/docs/upgrades#2018-08-23
> Fix subscription cancel()

- src/Billable.php
Now retrieve an invoice with ALL line items:
As per Stripe API documentation, when retrieving an invoice, you only retrieve "the first handful of those items", referring to the line items. Currently, the "findInvoice" method of the Billable only retrieves the invoice without retrieving all the lines. Therefore, when bills are generated, we get lots of missing lines and therefore it's impossible to check by our customers if their bill is OK.
This pull request solves this problem by simply retrieving up to 1000 lines of the invoice and replacing the lines object of the original invoice.
> [7.0] Bug solution for Issue #476

- src/Billable.php
In our previous pull request, for the invoice lines, we requested to modify the Chasier. We normally access to Stripe by previously setting the stripe key so we don't need to provide it for each new access to Stripe:
`\Stripe\Stripe::setApiKey(env('STRIPE_SECRET'));`
However, when making the request, we wanted to use the same method as you but we just now realised that by this way, the key is not set up for next access. So now we have included the Stripe key for the lines request to stripe:
`StripeInvoice::retrieve($id, $this->getStripeKey())`
Sorry for the inconvenience caused.
> [7.0] Bug solved: accessing the Stripe invoice lines with the Stripe Key. Issue #476 (#562)

- src/Http/Middleware/VerifyWebhookSignature.php
- tests/VerifyWebhookSignatureTest.php
This PR addresses #437.
A few notes on this PR:
- The configuration keys are assumed to exist, as they add on to the keys already defined in `services.php` in Laravel proper. Assuming this gets merged, those keys will eventually need to be added to that configuration file.
- There should be a default value set for the tolerance. [Stripe's default tolerance](https://stripe.com/docs/webhooks/signatures#replay-attacks) is `300` and seems a reasonable default.
- The middleware intentionally fails closed. If the user enables this middleware without a web-hook key set, we can assume that the user wants to enforce signatures and that the lack of a key is unintentional.
> Add VerifyWebhookSignature middleware.

- src/Subscription.php
- tests/CashierTest.php
This reverts https://github.com/laravel/cashier/pull/446
It doesn't really make sense to do this in the same operation. Swapping plans just means switching from one plan to the other. Changing the name of a subscription is just renaming it to a different context. Both have nothing to do with each other.
You can easily change the name of the subscription later on after the swap if you really want to. Changing this back keeps things more simple as well for swapping plans.
```php
$subscription = $subscription->swap(/* new plan */);
$subscription->name = 'new name';
$subscription->save();
```
> [8.0] Revert changing subscription name on plan swap

- src/Subscription.php
When the tax for a billable model changes it needs to be updated on its active subscription as well. This method provides an easy and convenient way to sync the billable model's tax to the subscription.
If this gets merged, I'll send in a PR to the docs as well to document this.
Background: there was a pretty large and longtime issue about tax changes not being applied to subscriptions https://github.com/laravel/cashier/issues/384. Turns out that Stripe subscriptions keep the original tax applied to them when you change the hardcoded value in `taxPercentage` on the billable user. What needs to happen is that users need to sync this change on their subscriptions if they want this tax change applied to their subscription. Otherwise Stripe will continue to use the old tax percentage value. …
> [7.0] Add updateTax method to sync tax to subscription

- tests/VerifyWebhookSignatureTest.php
PHPUnit has a newer version on master so we'll need to update the test case for the new `VerifyWebhookSignatureTest` tests.
> [8.0] Fix PHPUnit tests

- src/Http/Controllers/WebhookController.php
Hi,
Since there are some data on the Cashier database, like "trial_ends_at"/"quantity"/"ends_at"/"card_last_four", ... , if something is done on the Stripe dashboard, the database must be updated to keep consistency.
This PR will handle some more webhooks than the customer.subscription.deleted provided by Cashier :
- **customer.deleted** : when a customer is deleted on the Stripe dashboard, all his subscriptions must be cancelled in Cashier and his card informations + his stripe_id must be emptied.
- **customer.subscription.updated** : when the quantity, the plan, the trial_end are updated on the Stripe dashboard, the database must be updated too.
- **customer.updated** : if the default card of a user is updated on the Stripe Dashboard, the card_brand & card_last_four have to be updated. …
> [7.0] Handle more webhooks to keep database consistency

- composer.json
The [list of breaking changes](https://github.com/stripe/stripe-php/blob/master/CHANGELOG.md#600---2018-02-07) doesn't seem to impact this library.
The tests pass when I run them locally after this change, although it doesn't seem like the tests run on travis for this repo.
> [8.0] Update to v6 of the Stripe SDK

- src/Subscription.php
When a user has a cancelled subscription, and within a UI, swaps his plan selection, we must make sure to reactivate the subscription, otherwise, Cashier will take into account that the user has a "valid subscription", and the Stripe webhook that comes a few seconds later will immediately re-cancel the plan.
Adding `$subscription->cancel_at_period_end = false;` makes sure the plan is reactivated.
> [8.0] Make sure to reactivate subscription when swapping plans

- composer.json
- readme.md
- tests/CashierTest.php
This isn't needed anymore as the environment variables are loaded through the PHPUnit config file.
> [8.0] Remove dotenv library

- changes.md
- src/Billable.php
- src/SubscriptionBuilder.php
- tests/CashierTest.php
At the moment when using the `createAsStripeCustomer` method on a `Billable` entity, it could be that the creation of the customer succeeds but the updating of the card fails. When this happens it's impossible to know which customer was created in Stripe and therefor also impossible to remove this record again when the card update fails.
It seems that the `updateCard` method shouldn't be in the `createAsStripeCustomer` method as this couples these two API calls too much. If we remove the call from the `createAsStripeCustomer` method it can be used just for the purpose that it states. This will always return a `Customer` object and allow the developer to remove it again if the `updateCard` method after that fails.
This is a breaking change which will require developers to call the …
> [9.0] Do not update card in createAsStripeCustomer method

- src/Http/Controllers/WebhookController.php
- tests/CashierTest.php
- tests/WebhookControllerTest.php
This PR changes the way we check for events. It removes the API calls to Stripe for checking if an event exists and encourages the usage of the VerifyWebhookSignature middleware.
Verifying incoming webhook events by their signature is the recommended way by Stripe for making sure the event is legit. Making an API call to Stripe like we do now is a bit irrelevant as we can totally verify the legitemacy of the event by the signature alone. This saves us extra API calls to Stripe and should actually speed up webhooks.
This also solves the problem of the CASHIER_ENV env variable. Now that the middleware is only set on the controller when the webhook secret is filled in you have total control of turning it on and off for your use case.
The docs should be updated a little bit to encourage …
> [9.0] Encourage usage of VerifyWebhookSignature middleware

- .travis.yml
- composer.json
- src/CashierServiceProvider.php
Bumped dependencies to the minimum framework supported components and current supported PHP version of the framework. Also removed support for Symfony HttpKernel <4.0 since the framework itself doesn't supports it anymore.
> [9.0] Bump dependencies

- composer.json
> [9.0] Require ext-json for json_ function calls

- CHANGELOG.md
- src/Billable.php
- src/Subscription.php
- src/SubscriptionBuilder.php
I sent this PR with 2 changes because the 2nd one depends on the first one. Here's the commit summary for both:
When invoicing the customer while swapping plans, Cashier would invoice the customer for all its pending items instead of just the ones for the subscription. This PR fixes this by using the subscription field when creating an invoice to allow swapping a plan and the `incrementAndInvoice` method so the invoice at hand only invoices for the subscription and also uses the proper tax which is applied to the subscription.
When doing one off charges and immediately invoicing them you currently can't add extra options like a tax_percent to it which kind of limits you. By adding this extra option we can pass it to the invoice method with the parameter from the previous commit.
Fixes …
> [9.0] Fix invoicing subscriptions and extend one off charges

- src/Billable.php
$this->invoice returns a Stripe invoice object, and thus $invoiceFor too.
> Correct PHP Doc @return tag

- composer.json
This will allow CarbonImmutable and all features added in Carbon 2 and so use the default version from Laravel 5.8.
> [9.0] Allow Carbon 2

- src/Subscription.php
- tests/CashierTest.php
I've been using these in my applications and I had someone else ask about them, so I thought I would PR them and see if they might be handy having in the base package.
You can now apply query scopes based on the state of the subscription.
```php
$users = User::whereHas('subscriptions', function ($query) {
$query->whereName('gold')->onTrial();
})->get();
```
```php
$users = User::whereHas('subscriptions', function ($query) {
$query->whereName('gold')->active();
})->get();
```
```php
$users = User::whereHas('subscriptions', function ($query) {
$query->whereName('gold')->cancelled();
})->get();
```
```php
$users = User::whereHas('subscriptions', function ($query) {
$query->whereName('gold')->onGracePeriod();
})->get();
```
```php
$users = User::whereHas('subscriptions', function ($query) { …
```
> [9.0] Add subscription state scopes

- readme.md
- src/Subscription.php
- tests/CashierTest.php
This resolves #580 - you can now pass in parameters when swapping a subscription, such as a coupon.
I believe this would also resolve #550, but I haven't tested it.
Pull request to the master branch.
> [10.0] Add options to subscription swap

- readme.md
I realized that using and env variable in a CLI call isn't the best idea even though it's just a testing token. It's probably better that we use the `phpunit.xml` file like it was intended too.
> [9.0] Update testing instructions

- src/Billable.php
- tests/Integration/CashierTest.php
You can update the customer data in Stripe. 
Usage: `$user->updateStripeCustomer(['email' => 'updated@customer.com']);`
Check available parameters on [Stripe](https://stripe.com/docs/api/customers/update)
> [9.0] Able to update a Stripe customer

- UPGRADE.md
- src/Exceptions/SubscriptionCreationFailed.php
- src/SubscriptionBuilder.php
- tests/Integration/CashierTest.php
Stripe changed the way failed payments for subscriptions are handled in their 2019-03-14 API update: https://stripe.com/docs/upgrades#2019-03-14
This means subscriptions still get created if the payment fails but they get an incomplete status which gives the customer 23 hours to pay. Since Cashier expects a subscription to be properly paid for we should handle this scenario gracefully.
In the previous API version a card exception was thrown when a payment failed so the only thing that changes with this change is that it's a different exception that's thrown. What also happens is that the subscription gets cancelled immediately if we detect an incomplete subscription so the invoice is voided and the customer isn't billed anymore. No subscription gets added to the billable entity so the …
> [9.0] Handle incomplete subscriptions upon creation

- UPGRADE.md
- src/Subscription.php
- tests/Integration/CashierTest.php
Previously, when a plan swap was attempted and payment failed, the exception was cascaded to the end user and the update to the subscription in the app was not performed. However, the update to the subscription in Stripe itself was performed and the two states would be out of sync unless you implemented webhooks.
We've decided to catch the card failure exception and allow the plan swap to continue regardless of the failed payment. This leaves the subscription in a "past_due" state. This is because payment failure will be handled by Stripe and Stripe may attempt to retry the payment later on. When payment finally fails on its last attempt Stripe will send out a webhook to update the subscription in the way you specified in its settings: https://stripe.com/docs/billing/lifecycle#settings
> [9.0] Handle card failure in plan swap

- phpunit.xml.dist
- tests/Fixtures/User.php
- tests/Integration/ChargesTest.php
- tests/Integration/CustomerTest.php
- tests/Integration/IntegrationTestCase.php
- tests/Integration/SubscriptionsTest.php
- tests/Integration/WebhooksTest.php
- tests/Unit/CustomerTest.php
This PR splits up the large Cashier integration testcase into several smaller ones. This makes it more clear where to add tests and keeps a better overview of the covered functionality. It's also easier for new comers to know where they need to add tests.
I've also added an improvement so the customer in Stripe doesn't has a generic email address anymore but rather a description which matches the test method so we know which case was covered for which customer in Stripe's test data.
Before:
After:
A downsize to this is that the email addresses are rather long and take up quite some UI space. Here's an example of the event log:
If you want me to revert this or change this to something smaller let me know.
There's also a small downsize to this PR that because the test cases are now split …
> [10.0] Split and cleanup integration tests

- src/Cashier.php
This PR modifies the keys in the Cashier object. It adds the publishable key which we'll use in upcoming prs to prefill the JS widgets we'll use for Checkout and Payment Intents. It also properly refactors the key names to their clear equivalents from Stripe.
> [10.0] Add publishable key to Cashier

- src/Billable.php
- tests/Integration/CashierTest.php
Hello Laravel Team!
Summary:
-------------
This pull request addresses an issue where the `defaultCard()` method on the billable trait would throw an exception if the model was not created as a stripe customer.
Expected:
------------
Calling the `defaultCard()` method will return null if the user has no card on file, even when the billable model is not set up as a Stripe customer.
Actual:
--------
An exception is thrown:
`Stripe\Error\InvalidRequest: Could not determine which URL to request: Stripe\Customer instance has invalid ID: `.
Fix:
----
Checking to make sure that the billable model has a stripe ID before attempting to retrieve the model as a stripe customer, so we are not sending the Stripe PHP library invalid data.
> [9.0] Fixing `defaultCard()` exception when not Stripe customer

- composer.json
- database/migrations/2019_05_03_000001_create_customer_columns.php
- database/migrations/2019_05_03_000002_create_subscriptions_table.php
- phpunit.xml.dist
- src/Cashier.php
- src/CashierServiceProvider.php
- tests/Integration/IntegrationTestCase.php
This adds Cashier's migrations to the package itself so they're shipped with Cashier and can be published just like with Passport and Telescope. This also directly integrates the migrations into the test suite so they're tested. Orchestra testbench helps us to implement this.
I needed to update migrations for a future PR so I thought I'd implement this first.
Closes https://github.com/laravel/cashier/issues/639
> [10.0] Ship migrations with package

- tests/Integration/ChargesTest.php
- tests/Integration/IntegrationTestCase.php
- tests/Integration/SubscriptionsTest.php
- tests/Integration/WebhooksTest.php
It occurred to me that we could simply use the tokens Stripe provides to do the testing without making round trips to the api to create them ourselves.
See https://stripe.com/docs/testing#cards
> [10.0] Use Stripe tokens in tests

- routes/web.php
- src/CashierServiceProvider.php
- tests/Integration/WebhooksTest.php
This commit auto-registers the webhook endpoint with the package so the user doesn't has to do this themselves. They can still override it in their own routes file. Benefit of this is also that our integration test is now an actual endpoint test.
In an upcoming PR another route for payment intents will be added.
> [10.0] Register webhook route with the package

- src/SubscriptionBuilder.php
This removes the type check for a `Carbon` object in `trialUntil()` because those using Carbon 2 may also pass a `CarbonImmutable` object.
> [9.0] Remove strict type check for trialUntil()

- src/Billable.php
- src/Exceptions/InvalidStripeCustomer.php
- tests/Integration/InvoicesTest.php
In cases where methods are called which expect the billable entity to be a Stripe customer we'll first do a check from now on to see if that's the case. Otherwise we'll throw an exception to notify the developer that the billable entity must first be registered as a Stripe customer.
> [10.0] Throw exception when no stripe id is found

- src/Invoice.php
hasStartingBalance currently returns false if a customer has credit on its account. This is because Stripe returns the credit as a negative value. This subsequently also affects the subtotal. We'll use the same solution as the total and reverse the negative.
> [9.0] Fix hasStartingBalance and subtotal on Invoice

- src/Billable.php
- tests/Integration/ChargesTest.php
When a single charge is performed and the billable entity is a stripe customer it's not set when a custom source is passed. This PR fixes this behavior to allow single charges to stripe customers with a different payment source. If the payment source isn't attached to the customer the Stripe API call will fail. This is now also covered with tests.
> [10.0] Fix customer while charging

- composer.json
- resources/views/receipt.blade.php
- src/Cashier.php
- src/Invoice.php
- src/InvoiceItem.php
- tests/Unit/InvoiceTest.php
These changes utilize the Money library to format money values from the invoice and invoice line objects. It makes use of the invoice's currency to make sure there's no currency conflict when trying to display the values.
New Composer requirements:
- moneyphp/money: used for formatting money values
- symfony/intl: used for the above library to properly format money values
- (optional) ext-intl: used for more locales when formatting money values
This brings along some changes as well:
- Removed the $currencySymbol setting on the Cashier object along with the useCurrencySymbol and usesCurrencySymbol methods
- Removed the $symbol parameter from the useCurrency method on the Cashier object and its guessCurrencySymbol method
- Refactored the formatAmount method on the Cashier object to accept …
> [10.0] Refactor Invoices

- src/Http/Controllers/WebhookController.php
- tests/Integration/WebhooksTest.php
When resuming a cancelled subscription from Stripe, Cashier currently doesn't properly re-activates the subscription in the app. This change properly sets the ends_at value to null so the subscription is resumed.
See https://github.com/laravel/cashier/pull/629
Fixes https://github.com/laravel/cashier/issues/669
> [10.0] Fix subscription reactivation

- config/cashier.php
- phpunit.xml.dist
- readme.md
- src/Billable.php
- src/Cashier.php
- src/CashierServiceProvider.php
- src/Http/Controllers/WebhookController.php
- src/Http/Middleware/VerifyWebhookSignature.php
- src/Subscription.php
- tests/Integration/IntegrationTestCase.php
- tests/TestCase.php
- tests/Unit/InvoiceTest.php
- tests/Unit/VerifyWebhookSignatureTest.php
Cashier is at the moment one of the only Laravel packages which doesn't uses a config file. I think it would be better if it was more in line of the other packages by making use of one. This is what people are used to as well. These changes add a config file and cleans up the way configuration is handled within cashier.
An additional benefit is that the config for the stripe keys and web hooks is now included in Cashier itself and not outside of it anymore in the default `services.php` config file which ships with the Laravel skeleton. This keeps everything in exactly the place where you expect it to be and makes more sense.
Some configuration was kept in the `Cashier` class like the custom money formatting (closure which can't be in a config file) and the disabling of migrations (aligned …
> [10.0] Implement config file

- composer.json
Because it's unsupported. We already dropped it for the next laravel/framework release as well.
> [10.0] Drop Carbon 1 support

- src/Billable.php
- tests/Integration/ChargesTest.php
With Stripe's new Payment Method API, there's no way to set a default for single charges, only for invoices & billing purposes. Because of this requirement, it's best that the payment method is a required argument for the charge method.
```php
$user->charge(1000, $paymentMethod);
```
I've chosen to add this as the second parameter which reads a little bit better imo.
> [10.0] Require Payment Method for charge method

- src/Billable.php
- tests/Integration/PaymentMethodsTest.php
This will easily help users start a new setup intent session to set up payment methods.
More info here: https://stripe.com/docs/payments/cards/saving-cards#saving-card-without-payment
> [10.0] Implement SetupIntent create method

- src/Billable.php
- src/Http/Controllers/WebhookController.php
- src/PaymentMethod.php
- src/SubscriptionBuilder.php
- tests/Integration/ChargesTest.php
- tests/Integration/InvoicesTest.php
- tests/Integration/PaymentMethodsTest.php
- tests/Integration/SubscriptionsTest.php
This PR adds two additional methods to add and remove payment methods to the billable user. This way, apps can easily save more than one payment method for their store/checkout process. I've also renamed the default payment methods to make them more clear.
> [10.0] Additional payment methods functionality

- src/Billable.php
- tests/Integration/PaymentMethodsTest.php
Remove the customer parameter from the createSetupIntent method because new payment methods couldn't be associated with it.
> [10.0] Fix createSetupIntent

- src/Subscription.php
- tests/Integration/SubscriptionsTest.php
This adds an easy way to retrieve the latest payment for a subscription. This way it can be used to redirect to when a payment needs an extra action.
> [10.0] Add latestPayment method on Subscription

- database/migrations/2019_05_03_000002_create_subscriptions_table.php
- src/Billable.php
- src/Exceptions/SubscriptionUpdateFailure.php
- src/Http/Controllers/WebhookController.php
- src/Subscription.php
- src/SubscriptionBuilder.php
- tests/Integration/SubscriptionsTest.php
- tests/Integration/WebhooksTest.php
- tests/Unit/SubscriptionTest.php
These changes sync the Stripe status within Cashier. This allows us to make better decisions when payments fail. There's also a new `hasIncompletePayment` method on both the billable trait and subscription model so it's easy to determine if a payment needs to be completed.
Subscriptions with an `incomplete_expired` status will be deleted from the app because they serve no purpose anymore.
> [10.0] Improve stripe statuses

- src/Billable.php
- src/Subscription.php
- tests/Integration/SubscriptionsTest.php
These changes make sure that the `incrementAndInvoice` method also throws the SCA exceptions. It also adds a `swapAndInvoice` method which has the previous `swap` method behavior. The `swap` method now doesn't invoices the user immediately.
> [10.0] Fix subscription invoicing

- src/Subscription.php
- tests/Unit/SubscriptionTest.php
This makes sure only the "trialing" and "active" statuses of a subscription are considered active states. Doesn't requires apps to sync with Stripe statuses.
> [10.0] Refactor active subscription state

- src/Billable.php
- src/Subscription.php
- tests/Integration/InvoicesTest.php
This PR makes sure that an Cashier invoice object is returned when applicable instead of a Stripe invoice object.
> [10.0] Return invoice object when applicable

- src/Http/Controllers/WebhookController.php
If a payment is manually created from the Stripe dashboard, it is
possible that it will not be linked to a customer.
When this null stripeId is used to find a user record, it will find the
first customer record that does not have a stripeId in the database.
Adding an early exit will prevent this from happening, and stop these
null stripeId users being erroneously referenced in webhook handling.
> [9.0] Don't try and find a user when stripeId is null

- src/Invoice.php
Allows people to use a custom filename when downloading invoices. Works a little bit nicer then overwriting the headers.
Closes https://github.com/laravel/cashier/issues/715
> [10.0] Allow custom filename for invoice download

- src/Http/Controllers/WebhookController.php
Abstracted the way the response is made to a single method and made the missing method protected as well as it's not a public method which would be called externally.
> [10.0] Refactor webhook responses

- src/Subscription.php
Could be `null` when no payment was made yet.
> [10.0] Fix null return for latestPayment

- UPGRADE.md
This clarifies that if people are using Stripe's settings to send out payment notifications that they don't need to use Cashier's built in ones.
See https://github.com/laravel/cashier/issues/734
> [10.0] Clarify notifications with Stripe settings

- database/migrations/2019_05_03_000001_create_customer_columns.php
- database/migrations/2019_05_03_000002_create_subscriptions_table.php
Digging into the code I see that `users.stripe_id` and `subscriptions.stripe_status` are both used in the query builder to query data in the database. Additionally, `subscriptions.user_id` is used to load the relationship between users and subscriptions.
I can't see why you wouldn't want these rows to be indexed for faster lookups, especially with big datasets.
> [10.0] Add indexes to those columns used to lookup data in the database

- src/Subscription.php
syncStripeStatus method from Subscription model trying to update `status` column which is not correct. Correct column name is `stripe_status`.
> [10.0] syncStripeStatus trying to update incorrect status column

- src/Cashier.php
Since there are [no changes that affect Cashier](https://stripe.com/docs/upgrades?since=2019-05-16#api-changelog) we could use the latest Stripe API version (2019-08-14).
> [10.0] Update Stripe API version

- src/Billable.php
- src/Http/Controllers/WebhookController.php
- src/Subscription.php
- tests/Integration/PaymentMethodsTest.php
This adds support to overwrite the default Stripe options on the Billable model. This allows to customize the Stripe secret key amongst else. 
There's one concern: since there's no concept of a customer in the `PaymentController` so there's no way to overwrite the public and secret key there. I've thought about how to solve this but the only way is to pass the customer ID with the url. But that'd be a breaking change and a bit cumbersome to handle. The `PaymentController` can be easily overwritten though to do any customization here.
Closes https://github.com/laravel/cashier/issues/751
> [10.0] Multiple stripe accounts

- src/Cashier.php
- src/CashierServiceProvider.php
This sets the Stripe App info as detailed in https://stripe.com/docs/building-plugins#setappinfo
This makes sure Stripe can identify Cashier as a library and can contact us when critical updates to the API are made.
> [10.0] Set Stripe library info

- resources/views/payment.blade.php
If the user refreshes the page after successfully paying there will be no `#card-element` to mount to. Equally a cancelled payment requires no card payment. This means we should only mount the card element if payment has not succeeded or been cancelled.
> Only mount card element if payment has not succeeded or been cancelled

- src/SubscriptionBuilder.php
Set `off_session` parameter to `true` when creating a new subscription to tell Stripe that the recurring payments can be made off session. Without this parameter (which is `false` by default) all other payments will throw `IncompletePayment` exceptions.
This fixes issue #743.
> Set off_session parameter to true when creating a new subscription

- resources/views/payment.blade.php
> [10.x] Ensure SVG icons are visible even with a long success or error message

- resources/lang/en.json
- resources/views/payment.blade.php
> Add language line for full name placeholder

- .gitignore
- composer.json
- src/Billable.php
- src/Http/Middleware/VerifyWebhookSignature.php
- src/Invoice.php
- tests/Integration/IntegrationTestCase.php
The changes from v6 to v7 seem trivial to me, so I think this can be merged into Casher v10.
- Replace `Charge::refund()` to `Refund::create()`
- Replace `Customer::invoices()` to `Invoice::all()`
- Replace renamed exception classes
After upgrading to the v7 of the Stripe SDK, the `$customer->invoice_settings->default_payment_method` is null.
In that case, we don't need to update the Stripe customer, so we will just update the database.
The previous functionality has been kept as is.
According to #562, the invoice response contains only 10 line items, so we were manually fetching 1000 items.
But Stripe's pagination limit is 100 items, so that doesn't ensure that all the line items will be fetched.
Instead, we can use the `Stripe\Collection::autoPagingIterator()` which automatically …
> [10.x] Update Stripe SDK to v7

- src/Http/Middleware/VerifyWebhookSignature.php
- tests/Unit/VerifyWebhookSignatureTest.php
We can rid of the `\Illuminate\Contracts\Foundation\Application` dependency in the `VerifyWebhookSignature` constructor, by manually throwing a 403 exception.
This simplifies both the implementation and the tests, and it allows us to pass the message and the original exception to the exception handler.
> [10.x] Refactor handling of invalid webhook signatures

- src/Billable.php
- src/Invoice.php
- src/InvoiceItem.php
- src/PaymentMethod.php
Replacement for https://github.com/laravel/cashier/pull/800
Adds a new `findPaymentMethod` method to the Billable entity. Also adds a check in the `Invoice` and `PaymentMethod` object's constructors to make sure that no invalid objects can be build.
Pulled out the constructing of the objects outside the retrieval of the stripe object's try/catch blocks so these new exceptions can cascade through.
> [10.x] Add findPaymentMethod method

- config/cashier.php
- src/Cashier.php
- src/Subscription.php
- tests/Integration/SubscriptionsTest.php
This will add the ability to set past due subscriptions as active instead of the default inactive status. This will allow past due subscriptions to remain active until they're finally cancelled. 
Closes https://github.com/laravel/cashier/issues/768
> [10.x] Allow to set past due as active

- .styleci.yml
Alpha ordered imports will become the default for the laravel preset in a few minutes time on styleci.io.
> [10.0] Update .styleci.yml

- src/Events/WebhookHandled.php
- src/Events/WebhookReceived.php
- src/Http/Controllers/WebhookController.php
- tests/Unit/WebhookControllerTest.php
New implementation for https://github.com/laravel/cashier/pull/804 with an extra `WebhookReceived` event. This way anyone can hook into any event that was received.
> [10.x] Webhook events

- src/SubscriptionBuilder.php
Adds missing PHPDocs `@throws` for `create`/`add` methods on `Laravel\Cashier\SubscriptionBuilder` class. 
This aligns with what is described in `Upgrading To 10.0 From 9.0`: https://github.com/laravel/cashier/blob/master/UPGRADE.md#new-exceptions
> [10.x] Add Missing @throws tags

- src/Billable.php
Properly return `null` when an invoice or payment method can't be found.
Fixes https://github.com/laravel/cashier/issues/815
> [10.x] Properly return null for find methods

- src/Cashier.php
Nothing directly affects Cashier. Upgrade notices can be found here: https://stripe.com/docs/upgrades
> [11.x] Update to 2019-12-03 Stripe API version

- src/Billable.php
Stripe has added the ability to simply pass a payment intend ID to the refund api so we don't have to retrieve it first. We can simplify the refund method internals with this change.
Closes https://github.com/laravel/cashier/issues/825
> [10.x] Simplify refund method

- src/Billable.php
- tests/Integration/PaymentMethodsTest.php
- tests/Unit/CustomerTest.php
At the moment the `hasPaymentMethod` method will return false even if you just added one. Because customers can have payment methods without having a default one we'll need to differentiate and add a new dedicated `hasDefaultPaymentMethod` method. 
Sending this in to master for the obvious breaking change.
Closes https://github.com/laravel/cashier/issues/824
> [11.x] Add new has payment method

- src/PaymentMethod.php
Error message should say `The payment method [...]`, not `The invoice [...]`.
> [10.x] PaymentMethod: Fix typo in exception message

- src/Billable.php
- src/Exceptions/InvalidInvoice.php
- src/Exceptions/InvalidPaymentMethod.php
- src/Invoice.php
- src/PaymentMethod.php
- tests/Integration/InvoicesTest.php
Because of the changes made to the constructor of the Invoice object recently, the subsequent findInvoiceOrFail method didn't throw the AccessDeniedHttpException anymore and instead threw the new Exception from the constructor. I've now fixed this method to properly throw the AccessDeniedHttpException again.
I've also changed the Exception classes to two dedicated Exception classes which people can type-hint against.
Fixes https://github.com/laravel/cashier/issues/851
> [10.x] Fix findInvoiceOrFail behavior

- src/Billable.php
- src/Exceptions/InvalidPaymentMethod.php
- src/Exceptions/InvalidStripeCustomer.php
- src/Exceptions/PaymentActionRequired.php
- src/Exceptions/PaymentFailure.php
- src/Exceptions/SubscriptionUpdateFailure.php
- tests/Unit/CustomerTest.php
This will prevent usage of the `createAsStripeCustomer` when a stripe id is already set. Usage like this can be dangerous because a new stripe customer will be created and the link to the previous customer will be lost.
Fixes https://github.com/laravel/cashier/issues/862
> [10.x] Prevent createAsStripeCustomer when stripe_id is set

- src/Subscription.php
This method is only used because of the webhook controller events and shouldn't be used outside the library. It's not documented for this reason.
See https://github.com/laravel/cashier/issues/864
> [10.x] Mark markAsCancelled as internal

- src/Cashier.php
- src/Http/Controllers/WebhookController.php
There was no convenient way to grab the relevant user from a webhook event (like `customer.subscription.created` without copying the code from WebhookController.
Move that method to the Cashier class and update the calls in WebhookController.
Now in my webhook controller I can do:
```php
$user = Cashier::findBillable($payload['data']['object']['id']);
```
Updated previous PR as per Dries' comments in https://github.com/laravel/cashier/pull/867/.
> [10.x] Ability to get User by stripe id

- src/SubscriptionBuilder.php
- tests/Integration/SubscriptionsTest.php
This is a pull request to support additional subscriptions options, and resolves #787 
I was thinking about passing $subscriptionOptions and $customer into the buildPayload function, but ultimately decided to keep the PR simple. Let me know if you'd prefer the array merge to happen in the buildPayload function.
> [11.x] Add subscription options + test

- src/Billable.php
In the documentation https://laravel.com/docs/6.x/billing#payments-requiring-additional-confirmation it's stated the the methods `charge` `invoice` and `invoiceFor` on a user can throw `IncompletePayment` exceptions but the methods documention wasn't marked as such.
This PR just adds those `@throws` tags to the methods.
> Add @throws declaration to methods on Billable which can throw Payment exceptions

- src/InvoiceLineItem.php
This fixes a bug where tax rates weren't showing for non-tax except customers and only inclusive tax was applied.
Fixes https://github.com/laravel/cashier/issues/854
> [11.x] Fix a bug with tax rates

- resources/views/receipt.blade.php
This changes the invoice number on receipts to the actual invoice number in Stripe. The current id is Stripe internal identifier for doing API requests while the invoice number is the one set in Stripe to identify the invoice as an incremental number.
Sending this in to master because of the change in behavior.
Closes https://github.com/laravel/cashier/issues/845
> [11.x] Use proper invoice number

- resources/views/payment.blade.php
This replaces [the deprecated method](https://stripe.com/docs/js/deprecated/handle_card_payment_element) with [the new one](https://stripe.com/docs/js/payment_intents/confirm_card_payment#stripe_confirm_card_payment-data-payment_method).
Closes https://github.com/laravel/cashier/issues/844
> [10.x] Update payment page with new JS method

- src/Billable.php
The idea behind these changes is that these methods should still be able to be used even if the Billable model isn't a Stripe customer yet. By default we can assume that when a Billable model isn't a Stripe customer yet that no invoices, payment methods or upcoming invoice exists yet.
> [11.x] Loosen exception throwing

- src/Subscription.php
- tests/Integration/SubscriptionsTest.php
- tests/Unit/SubscriptionTest.php
This will allow for extending trial periods on existing subscriptions to allow customers some additional time after they've already subscribed.
Closes https://github.com/laravel/cashier/issues/550
> [10.x] Implement extending trials

- src/Subscription.php
Follow up for #884. I realized that allowing to prevent prorating when extending trials kind of defeats the purpose of the feature.
> [10.x] Do not allow changing prorating when extending trials

- src/Billable.php
Allows to easily set a custom filename when downloading an invoice directly from a Billable model.
> [11.x] Allow for custom filename with downloadInvoice method

- resources/views/receipt.blade.php
- src/Billable.php
Email address isn't required when creating a customer in Stripe. It can be added at a later time or not at all. Email capabilities from Stripe out aren't available in this case but that's not always needed.
This also allows to customize which attribute on the model should be used for the email address.
Closes https://github.com/laravel/cashier/issues/485
> [10.x] Make email optional

- src/Subscription.php
- tests/Integration/SubscriptionsTest.php
Re-send of https://github.com/laravel/cashier/pull/717
This will allow to re-enable prorating when doing multiple swaps in one request. Also adds tests for proration.
Closes https://github.com/laravel/cashier/issues/647
> [10.x] Re-enable proration

- resources/views/payment.blade.php
At the moment when you go back from a payment page after a successful single charge there's no way of knowing if the payment was successful. These changes allow the go back button to send a status message and succes query parameters upon succes or failure.
Closes https://github.com/laravel/cashier/issues/848
> [10.x] Redirect with status

- src/Invoice.php
This adds the `X-Vapor-Base64-Encode` header to the 9.x release. We currently use Cashier, and are unable to upgrade to 10.x due to several infrastructure blockers (they're actively being worked on). This is to add support out of the box so we don't have to extend Cashier.
I'm sure this will help others who are in a similar situation, but can't immediately upgrade to 10.x.
> [9.x] add X-Vapor-Base64-Encode header

- src/Subscription.php
This updates the prorations of subscriptions with the new `proration_behavior` field. No breaking changes.
I've made the decision to not make use of the `always_invoice` value  and [pending updates](https://stripe.com/docs/billing/subscriptions/pending-updates) for now. I think we can apply that on the `swapAndInvoice` method but there's all sorts of complications when doing it which I'd rather investigate at a different time. 
Closes https://github.com/laravel/cashier/issues/902
> [11.x] Implement new proration_behavior field

- database/migrations/2019_05_03_000002_create_subscriptions_table.php
- database/migrations/2019_05_03_000003_create_subscription_items_table.php
- src/Concerns/ManagesSubscriptions.php
- src/Exceptions/SubscriptionUpdateFailure.php
- src/Http/Controllers/WebhookController.php
- src/Subscription.php
- src/SubscriptionBuilder.php
- src/SubscriptionItem.php
- tests/Feature/FeatureTestCase.php
- tests/Feature/MultiplanSubscriptionsTest.php
- tests/Feature/WebhooksTest.php
- tests/Fixtures/User.php
- tests/Unit/SubscriptionTest.php
This PR implements multiplan subscription support into Cashier.
Some examples:
```php
// Add a new plan to a subscription...
$subscription->addPlan($plan);
// Add a new plan to a subscription and invoice immediately...
$subscription->addPlanAndInvoice($plan);
// Add a new plan with a specific quantity...
$subscription->addPlan($plan, $quantity);
// Remove a plan from a subscription...
$subscription->removePlan($plan);
// Update quantities for plans...
$subscription->updateQuantity($quantity, $plan);
```
Stripe docs: https://stripe.com/docs/billing/subscriptions/multiplan
Stripe API: https://stripe.com/docs/api/subscription_items
Closes https://github.com/laravel/cashier/issues/397
> [11.x] Multiplan subscriptions

- src/Concerns/ManagesSubscriptions.php
- src/Concerns/Prorates.php
- src/Exceptions/SubscriptionUpdateFailure.php
- src/Http/Controllers/WebhookController.php
- src/Subscription.php
- src/SubscriptionBuilder.php
- src/SubscriptionItem.php
- tests/Feature/MultiplanSubscriptionsTest.php
This PR adds support for multiplan swapping.
```php
// Swap multiple plans at the same time...
$subscription->swap(['new-plan', 'other-plan']);
// Invoice immediately...
$subscription->swapAndInvoice(['new-plan', 'other-plan']);
// Provide extra subscription options...
$subscription->swap(
['new-plan', 'other-plan'],
['metadata' => ['key' => 'value']]
);
// Provide extra subscription item options...
$subscription->swap(
['new-plan' => ['quantity' => 5], 'other-plan'],
['metadata' => ['key' => 'value']]
);
```
Any old plan which isn't in the list during swapping will be removed from the subscription. Any existing plan will be kept.
You also swap individual subscription items:
```php
// Swap an individual subscription item's plan to a different one... …
```
> [11.x] Multiplan swapping

- src/Concerns/ManagesSubscriptions.php
- src/Subscription.php
- src/SubscriptionBuilder.php
After discussing with @themsaid we decided to re-add the old `taxPercentage` way of defining tax rates to make it easier for people to migrate. Tax Rates will remain the primary way of defining taxes and we won't re-add the `taxPercentage` to the documentation. All `taxPercentage` calls are also marked as deprecated.
> [11.x] Re-add tax percentage

- src/Subscription.php
- src/SubscriptionItem.php
- tests/Feature/MultiplanSubscriptionsTest.php
It turned out that the current increment and decrement methods still derived the quantity from the main subscription instead of the subscription items when a plan was passed. I refactored the code a bit and moved the quantity updates to the subscription items themselves. The code is a whole lot cleaner now. 
No breaking changes.
Fixes https://github.com/laravel/cashier/issues/917
> [11.x] Fix quantity methods

- src/Subscription.php
Fixes https://github.com/laravel/cashier/issues/922
> [11.x] Fix add and remove plan

- src/Concerns/Prorates.php
- src/Subscription.php
- tests/Feature/MultiplanSubscriptionsTest.php
Pass through the `$prorate` state of the subscription to the subscription item before doing the prorating.
Fixes https://github.com/laravel/cashier/issues/923
> [11.x] Fix quantity prorating

- src/Subscription.php
- tests/Feature/MultiplanSubscriptionsTest.php
As suspected, the plan parameter here is causing some issues for multiplan subscriptions. I think it can be safely removed without affecting existing code. 
Added a test that verifies resuming canceled multiplan subscriptions.
Fixes https://github.com/laravel/cashier/issues/921
> [11.x] Fix multiplan subscription swapping

- src/Concerns/ManagesInvoices.php
Replaces https://github.com/laravel/cashier/pull/935
Resent to run the test suite.
> [11.x] Send invoice

- composer.json
- src/Concerns/ManagesCustomer.php
- tests/Feature/CustomerTest.php
Adds `customerPortalUrl` and `redirectToCustomerPortal` methods.
I was thinking it would be cool if we shipped with a CustomerController and route out of the box so you could just do something like `route('cashier.customer.portal')` but that might be breaking and we'd need to know how to handle multiple guards.
> [12.x] Stripe Customer Portal

- src/Subscription.php
At the moment `cancelNow` will immediately cancel the subscription and prevent any new invoices. These changes allow for two things:
Send a final invoice for any remaining used resources:
```php
$subscription->cancelNowAndInvoice();
```
Prorate any remaining time to the customer's balance:
```php
$subscription->prorate()->cancelNow();
```
Closes https://github.com/laravel/cashier-stripe/issues/974
> [12.x] Apply prorate and invoice_now for cancelNow

- src/Http/Middleware/VerifyRedirectUrl.php
- tests/Unit/VerifyRedirectUrlTest.php
Makes sure that the checking fails when an invalid url was passed.
> [12.x] Fail url checking when url is invalid

- resources/views/payment.blade.php
- src/Http/Controllers/PaymentController.php
Replaces https://github.com/laravel/cashier-stripe/pull/982 as I couldn't push to the OP's branch.
This PR fixes the issue where a payment confirmation would always add a new card. With the new behavior it differentiates between two possible failures: requires action (just confirmation of the payment) or requires payment method (new payment method needs to be set). Both are now properly handled.
Fixes https://github.com/laravel/cashier-stripe/issues/971
> [12.x] Fix double payment method

- src/Subscription.php
- tests/Feature/SubscriptionsTest.php
This PR fixes the scenario for single plan subscriptions doing swaps but where the quantity may get lost during the swapping. It also fixes a scenario where you'd explicitly want to set a new quantity during swapping.
Fixes https://github.com/laravel/cashier-stripe/issues/990
> [12.x] Fix quantity preserving

- src/Concerns/ManagesSubscriptions.php
- tests/Feature/SubscriptionsTest.php
- tests/Unit/CustomerTest.php
Port of https://github.com/laravel/cashier-paddle/pull/69 for Cashier Stripe. Credits to @yoeriboven.
Tests are failing because of rate limiting. Passing locally.
> [12.x] Implement trialEndsAt

- .github/workflows/tests.yml
- composer.json
This adds support for PHP 8.
_Tests failing because of missing Stripe API Key; [see successful runs on my fork](https://github.com/mmachatschek/cashier-stripe/actions/runs/337253590)_
> [12.x] Support PHP 8

- src/Http/Middleware/VerifyRedirectUrl.php
- tests/Unit/VerifyRedirectUrlTest.php
This PR is to copy a bug fix that was committed to the `12.x` branch into the `11.x` branch.
See https://github.com/laravel/cashier-stripe/pull/984/
The current version of `laravel/spark-aurelius` (11.0) currently requires `"laravel/cashier": "^11.0"`, in which this bug is still present.
I am aware that the Laravel Contribution guide specifies that all bug fixes should only be committed in the latest stable branch. However, since the latest stable branch of `laravel/spark-aurelius` requires an older version of `laravel/cashier`, I believe that it would be appropriate to perform this patch on the older branch.
> [11.x] Fail url checking when url is invalid (#984)

- src/SubscriptionBuilder.php
This adds a `withPromotionCode` method to the subscription builder in addition to the `withCoupon` method in order to provide for Stripe's new promotion codes. When using this method, the API ID for the promotion code needs to be passed, not the promotion code itself.
```php
$subscription = Auth::user()->newSubscription('default', 'price_xxx')
->withPromotionCode('promo_xxx')
->create($paymentMethod);
```
> [12.x] Add withPromotionCode method

- src/Subscription.php
I recently updated my Cashier implementation to migrate customers from the `tax_percent` property to Stripe's [Tax Rates](https://stripe.com/docs/billing/taxes/tax-rates).
I tried using the `syncTaxRates()` function to update existing customer subscriptions, but found this would always prorate by default. The screenshot below from Stripe's dashboard shows what was happening to existing customers with existing subscriptions when `$user->subscription('default')->syncTaxRates();` was being called. A pair of "Remaining time" invoice items were being added unexpectedly:
This change now allows users to call `$user->subscription('default')->noProrate()->syncTaxRates();`, should they wish, to prevent prorating when syncing tax rates.
This shouldn't break existing code, as the default behaviour is …
> [12.x] Fix proration behaviour being forced when syncing tax rates

- composer.json
- src/Invoice.php
This PR fixes (local) image support when using the invoice PDF feature.
With the release of **Dompdf** [0.8.6](https://github.com/dompdf/dompdf/releases/tag/v0.8.6), a disclosure vulnerability was fixed. By doing so, a breaking change was introduced: when generating a PDF without the proper configuration, only resources within the dompdf folder itself are accessible. As a result, when using Cashier to generate a PDF invoice, the use of a local image (for example, a logo) is blocked.
Consider this example:
```php
// receipt.blade.php
...
...
```
Before 0.8.6, this worked fine. As of 0.8.6, only resources in the vendor/dompdf directory are allowed, causing any file in `public_path` (or any other path in your Laravel app, for that matter) to be rejected.
The solution is to configure Dompdf …
> [12.x] Fix image support in PDF invoices

- resources/views/checkout.blade.php
- src/Checkout.php
- src/Concerns/PerformsCharges.php
- src/Http/Controllers/WebhookController.php
- src/Subscription.php
- src/SubscriptionBuilder.php
- tests/Feature/CheckoutTest.php
This PR adds functionality for Stripe checkout and is a continuation of https://github.com/laravel/cashier-stripe/pull/652. All concerns on the original PR have been resolved since.
Docs: https://github.com/laravel/docs/pull/6465
Checking out a single priced product:
```php
$checkout = Auth::user()->checkout('price_xxx');
return view('checkout', compact('checkout'));
```
Checking out a single priced product with a specific quantity:
```php
$checkout = Auth::user()->checkout(['price_xxx' => 5]);
return view('checkout', compact('checkout'));
```
Checking out multiple priced products and optionally assign quantities to some:
```php
$checkout = Auth::user()->checkout(['price_xxx' => 5, 'price_yyy']);
return view('checkout', compact('checkout'));
```
Checking out a single priced product and …
> [12.x] Stripe Checkout Support

- src/Invoice.php
`invoiceLineItemsByType` actually returns an array and not a collection.
> [12.x] Fix return type for invoice line items

- src/Http/Controllers/WebhookController.php
- tests/Feature/WebhooksTest.php
Allows subscriptions to be created from the Stripe dashboard. The `newSubscriptionName` allows users to configure a different default key when overriding the `WebhookController`. 
The only limitation with this PR is that it won't work in situations where you have more than one type of subscription and need to differentiate between the names.
> [12.x] Allow Stripe dashboard subscriptions

- src/Subscription.php
- tests/Feature/SubscriptionsTest.php
Does what it says on the tin
```php
$subscription = $user->newSubscription('main', 'plan_123')
->trialDays(10)
->create($paymentMethod);
$subscription->endTrial();
```
> [12.x] End trial method

- src/Concerns/ManagesSubscriptions.php
- tests/Feature/MeteredBillingTest.php
In the next major Cashier version we can make plans optional for `newSubscription` because features like metered billing require a slightly different flow.
> [13.x] Make plans optional for newSubscription

- src/Cashier.php
- src/Concerns/ManagesSubscriptions.php
- src/Subscription.php
- src/SubscriptionItem.php
Allows people to swap the base models in the same fashion as Passport & Sanctum.
> [12.x] Allow model swapping

- .github/workflows/tests.yml
- composer.json
Drop support for PHP 7.2 in the next major Cashier release.
> [13.x] Drop PHP 7.2 support

- .github/workflows/tests.yml
- composer.json
Drop support for older Laravel versions in the next Cashier release.
> [13.x] Drop Laravel 6 & 7 support

- resources/views/checkout.blade.php
Fixes #1069 
If the class is set, the styles would overwrite the class styles, because we're showing default styles because class isset.
Now you can do something like:
```
{{ $checkout->button('Pay For Job', [
'class' => 'bg-blue-100 text-sm px-4 py-2',
'styles' => 'other styles here that don't clash with classes.'
]) }}
```
> [12.x] Fix styles overwriting checkout button when class is set

- database/migrations/2019_05_03_000001_create_customer_columns.php
- src/Concerns/ManagesPaymentMethods.php
- src/Http/Controllers/WebhookController.php
- tests/Feature/PaymentMethodsTest.php
- tests/Feature/SubscriptionsTest.php
- tests/Unit/CustomerTest.php
This PR provides support for all payment methods provided by Stripe. Thanks to @simonhir. 
By allowing people to choose the type when calling the payment methods methods (phew!) they can cycle through the ones they need. Payment method types will be set as the `card_brand` on the customer record unless it's a card. In that case it will be the actual card brand. If a payment method type have a `last4` param it'll be synced to the `card_last_four`.
```php
$cards = $user->paymentMethods('card');
$sepaDebits = $user->paymentMethods('sepa_debit');
```
This does not include changes needed to be payment page which will need to be tackled in a different PR. There's already a PR from the past by @lsmith77 that looks promising: https://github.com/laravel/cashier-stripe/pull/893
Fixes #507
> [13.x] Support more payment method types

- src/Cashier.php
- src/Concerns/ManagesCustomer.php
- src/Concerns/ManagesInvoices.php
- src/Concerns/ManagesPaymentMethods.php
- src/Concerns/ManagesSubscriptions.php
- src/Http/Controllers/WebhookController.php
- tests/Feature/SubscriptionsTest.php
Replaces the word "entity" with the more appropriate "customer" phrasing.
> [12.x] Replace entity with customer

- src/Concerns/ManagesPaymentMethods.php
- tests/Feature/PaymentMethodsTest.php
This PR removes all support for the legacy sources API. Cashier will from now on only use the new Payment Methods API.
> [13.x] Remove legacy sources support

- src/Http/Controllers/WebhookController.php
- tests/Unit/WebhookControllerTest.php
Fixes https://github.com/laravel/cashier-stripe/issues/1079
> [12.x] Fix missing method on WebhookController

- .github/workflows/tests.yml
- resources/views/payment.blade.php
- src/Http/Controllers/PaymentController.php
- src/Http/Middleware/VerifyRedirectUrl.php
- tests/Unit/VerifyRedirectUrlTest.php
This will allow relative urls for the redirect like we use in Spark: `?redirect=/billing`.
Also contains the ubuntu-18.04 env update for the CI builds.
> [12.x] Allow relative urls for redirect

- resources/views/receipt.blade.php
This PR fixes an issue with the generated receipts using DomPdf to properly display UTF-8 characters. It introduces the DejaVu Sans font that ships with DomPdf. It was specifically added to DomPdf to display UTF-8 characters. The receipts will, however, have a different look and feel because of this. Personally I think they look better.
More info: https://github.com/dompdf/dompdf/wiki/About-Fonts-and-Character-Encoding
Before:
After:
> [12.x] Use DejaVu Sans for receipts

- src/Http/Controllers/WebhookController.php
- tests/Feature/WebhooksTest.php
Reproduction:
1. Add subscription to user
2. Cancel subscription with custom date on Stripe Dashboard
Expected:
- `ends_at` is set as in the stripe subscription model property `cancel_at`
Outcome:
- `ends_at` property in subscription model is null
> [12.x] Subscription Update Webhook bugfix

- src/Payment.php
In some cases, users needs to confirm a payment or setup intent. This is probably due to the Stripe customer account having a card added through the Stripe dashboard (Unconfirmed, only speculating).
You can currently just do
```php
$payment->status === \Stripe\PaymentIntent::STATUS_REQUIRES_CONFIRMATION
```
However, this `requiresConfirmation` method would bring this status inline with the other statuses
> [12.x] requiresConfirmation status helper method

- resources/views/receipt.blade.php
This updates the default shipped receipt with the invoice line item description rather than what we roll of our own. It duplicates the amount paid a bit but overall more properly displays the bought product. 
There could be a breaking change here in the sense that a product description in Stripe might differ from a product description in your app. In that sense we could also target this change to master. 
I'd argue that with the current support of multi plan subscriptions it's best to make this change as it's otherwise not possible to know about which product the invoice is about wen you're subscribed to multiple products.
Before:
After:
> [12.x] Update description on receipt

- resources/views/payment.blade.php
This PR does a couple of things:
- Update Tailwind to v2
- Some minor styling tweaks
- Adds `requires_confirmation` as a valid payment type to confirm payments on this page
Closes https://github.com/laravel/cashier-stripe/issues/1092
> [12.x] Update payment page

- config/cashier.php
- database/factories/SubscriptionFactory.php
- phpunit.xml.dist
- src/Cashier.php
- src/Concerns/ManagesCustomer.php
- src/Subscription.php
- tests/Feature/LoggerTest.php
- tests/TestCase.php
This will remove the model config option in favor of setting a static property on the Cashier class. This will make setting the custom model for the billable entity the same as we do it in the rest of Cashier and the same as we do it in all our other first party packages. It also makes the new Models namespace of Laravel 8 the default one.
> [13.x] Refactor model config option

- src/Subscription.php
- tests/Feature/SubscriptionsTest.php
This implements a `cancelAt` method on the `Subscription` model in a similar fashion as we did for Cashier Paddle. It'll allow subscriptions to be cancelled at an exact moment in the future.
```php
$subscription->cancelAt(now()->addDays(10));
```
Implements https://github.com/laravel/cashier-stripe/issues/1105
> [12.x] Implement cancelAt

- composer.json
`symfony/intl` is 16MB and is not even used by this package code or any of its dependencies. In 13.x, we should probably remove this entirely, since `ext-intl` is already suggested.
> [12.x] Replace super heavy symfony/intl dependency

- resources/views/receipt.blade.php
- src/Invoice.php
Uses the human readable description that's defined in the dashboard first before falling back on the coupon ID. This is also the default Stripe behavior on their receipts/invoices.
Implements https://github.com/laravel/cashier-stripe/issues/1117
> [12.x] Fix coupon label on receipts

- src/SubscriptionBuilder.php
This PR extracts the portion that creates the Eloquent Subscription model and the SubscriptionItem models into a separate method. This is useful if people want to overwrite this to, for example, add extra fields upon creation.
Implements https://github.com/laravel/cashier-stripe/issues/1122
> [12.x] Extract creating subscription to a separate method

- src/Concerns/ManagesSubscriptions.php
- tests/Feature/SubscriptionsTest.php
Closes #1128 
The `trialEndsAt` returns the `trial_ends_at` attribute by default if there are no arguments passed through and the user is indeed on a generic trial. Without the `onGenericTrial` check, the function will always return `trial_ends_at` if no arguments were passed through.
The `trialEndsAt` function also returns `trial_ends_at` as a fallback because there may be a use case that an application expects a historical date from `trialEndsAt`.
> [13.x] Fix trialEndsAt more closely represents onTrial

- resources/views/receipt.blade.php
The current "Organization" is confusing and can lead users into believing they mean the same thing even though it indicates two very different things on the receipt (the vendor & the customer). I've updated the descriptions to make these more clear.
> [12.x] Fix receipt comments

- resources/views/receipt.blade.php
- src/Concerns/ManagesInvoices.php
- src/Invoice.php
This PR will refactor receipts so it'll pull more data from Stripe directly. There's now more info on the receipts like customer address, tax ids, etc. Also the `description`/memo field is added automatically. The vendor details still need to be provided explicitly because Stripe doesn't adds that historical data to the invoice object.
There's almost no breaking changes. Things that I can think of are the fact that the customer name (previously the `to:` info) is now derived directly from the Stripe customer. `vendor` and `product` parameters are now optional instead of required.
Here's a before / after of the receipts:
Closes https://github.com/laravel/cashier-stripe/issues/952
> [13.x] Refactor receipts with more data from Stripe

- src/Concerns/ManagesCustomer.php
- src/Concerns/ManagesInvoices.php
This PR adds some methods to easily manage TaxID's on a customer. This is useful for keeping this data in Stripe so it also appears on its invoices an later in our own receipts like in https://github.com/laravel/cashier-stripe/pull/1136
Usage:
```php
// Return all of the customer's TaxIDs in an collection instance...
$user->taxIds(); 
// Retrieve a specific TaxID from the customer...
$user->findTaxId('txi_IzcmyhZukd4oKD');
// Create a new TaxID for the customer...
$user->createTaxId($type, $value);
// Delete a TaxID from the customer...
$user->deleteTaxId('txi_IzcmyhZukd4oKD');
```
Closes https://github.com/laravel/cashier-stripe/issues/1071
> [12.x] Add methods for managing TaxIDs

- src/Subscription.php
This will allow the usage of proration behavior when extending trials:
```php
$subscription = $subscription->noProrate()->extendTrail($date);
```
Closes https://github.com/laravel/cashier-stripe/issues/1149
> [12.x] Prorations and extending trials

- resources/views/receipt.blade.php
- src/Cashier.php
- src/Checkout.php
- src/Concerns/ManagesInvoices.php
- src/Concerns/ManagesPaymentMethods.php
- src/Concerns/PerformsCharges.php
- src/Coupon.php
- src/Discount.php
- src/Invoice.php
- src/InvoiceLineItem.php
- src/Payment.php
- src/PaymentMethod.php
- src/Subscription.php
- src/SubscriptionBuilder.php
- src/Tax.php
- tests/Feature/SubscriptionsTest.php
- tests/Unit/InvoiceTest.php
This PR implements multiple discount support for receipts. With these changes, all discounts on a receipt are properly displayed with their name set up through Stripe as well as their percentage or amount off.
Here's an example of multiple discounts:
The general amount of is calculated first. Afterwards, individual discounts are applied per specific product they apply for.
Here's the equivalent Stripe receipt:
Some other changes in this PR:
- I've refactored the way extra parameters on the Stripe Invoice object are expanded. They are now only expanded when called upon and the data is cached internally on the object.
- A new `Discount` and `Coupon` object were introduced to wrap the related Stripe objects.
- Cleaned up some inconsistencies with collection class instantiation and `is_null` …
> [13.x] Multiple discounts on receipts

- src/Subscription.php
- src/SubscriptionItem.php
- tests/Feature/FeatureTestCase.php
This resolves a small discrepancy with other methods which have options in their method signatures.
> [13.x] Add array types

- src/Subscription.php
- src/SubscriptionItem.php
- tests/Feature/SubscriptionsTest.php
This PR introduces payment exception throwing for quantity methods if payments go amis. This is the same behavior that's already implemented for swapping plans. 
Closes https://github.com/laravel/cashier-stripe/issues/1027
> [13.x] Throw payment exception for quantity methods

- src/Concerns/ManagesInvoices.php
- src/Subscription.php
- tests/Feature/SubscriptionsTest.php
Noticed this issue and thought I would suggest a PR since I've done something similar in my current project. Nothing fancy. Just a very basic method that has the same signature as the `swap` method
```php
$upcomingInvoice = $subscription->previewInvoice('price_to_swap')
```
Closes #1142
> [13.x] Preview upcoming invoice

- src/SubscriptionBuilder.php
When creating a Stripe Session checkout there's a minimum amount of time of 48 hours in which the user needs to be given a trial period. Because there could be a slight delay between the time the code is run and the API endpoint is hit, the timestamp could already be less than 48 hours away. Therefor I've tried to fix this by adding an additional 10 seconds of trial time to account for these execution delays.
> [12.x] Add extra 10 seconds of trial time

- src/SubscriptionItem.php
This PR refactors the way payments for subscription items are validated a bit (tests were failing atm) and it also adds exception throwing to plan swapping for subscription items. 
I noticed this wasn't implemented yet for subscription items either.
> [13.x] Throw payment exceptions on item swap

- src/Concerns/ManagesInvoices.php
- tests/Feature/InvoicesTest.php
Apparently if you use a quantity here you're required to use `unit_amount` instead of `amount`. No idea why no-one ever stumbled on this before.
Fixes https://github.com/laravel/cashier-stripe/issues/1153
> [12.x] Fix adding invoice item with quantities

- src/Cashier.php
- src/Checkout.php
- src/Concerns/ManagesCustomer.php
- src/Concerns/ManagesInvoices.php
- src/Concerns/ManagesPaymentMethods.php
- src/Concerns/PerformsCharges.php
- src/Http/Controllers/PaymentController.php
- src/Http/Controllers/WebhookController.php
- src/Invoice.php
- src/Payment.php
- src/Subscription.php
- src/SubscriptionBuilder.php
- src/SubscriptionItem.php
- tests/Feature/CheckoutTest.php
- tests/Feature/FeatureTestCase.php
- tests/Feature/MeteredBillingTest.php
- tests/Feature/MultipriceSubscriptionsTest.php
- tests/Feature/PaymentMethodsTest.php
- tests/Feature/PendingUpdatesTest.php
- tests/Feature/SubscriptionsTest.php
- tests/Feature/WebhooksTest.php
- tests/Fixtures/User.php
This PR refactors the way API requests to Stripe are made by implementing their new recommended way of using the `StripeClient` object. There are a couple of advantages to this:
- `StripeClient` more explicitly throws exceptions when you send malformed payloads instead of failing silently like before
- Simplifies things. No more passing extra options to each API request.
- We stay up to date with Stripe's recommended way of using the SDK
The upgrade path for existing users should be easy. No public API was changed. Only if you were overwriting the `stripeOptions` method you'll need to overwrite the `stripe` method now instead (which I suspect almost no-one is doing). 
Closes https://github.com/laravel/cashier-stripe/issues/939
> [13.x] Stripe SDK refactor

- src/Http/Controllers/PaymentController.php
Reverts a small change by https://github.com/laravel/cashier-stripe/pull/1120. This will allow people who have already exported the `payment.blade.php` file to have a seamless transition.
> [13.x] Revert breaking change to payment controller

- tests/Feature/SubscriptionsTest.php
While implementing #1129 in laravel/cashier-paddle I noticed the test was giving a false positive.
When removing the added code in `ManagesSubscriptions` the test still worked fine.
This is because the `name` parameter of `trialEndsAt` defaults to `default`.
The test however was using `main` as the subscription name.
This is fixed by changing the subscription name to `default` as well.
> [13.x] Fixed false positive test

- UPGRADE.md
The receipt changes mostly add new design updates. There aren't immediate breaking changes. If you wish, we could scratch the whole section.
> [13.x] Update UPGRADE.md

- src/Subscription.php
Two extra convenience methods for adding metered plans.
See https://github.com/laravel/cashier-stripe/issues/1175
> [13.x] Add new metered price methods

- src/Concerns/AllowsCoupons.php
- src/Concerns/PerformsCharges.php
- src/SubscriptionBuilder.php
- tests/Feature/CheckoutTest.php
One more PR for v13. This PR extracts coupon functionality to an `AllowsCoupons` trait. It consolidates code over two places where we were using it and keeps classes like the `SubscriptionBuilder` tidy. This PR also additionally allows for `withCoupon` to be used on a customer before creating a Stripe Checkout session:
```php
$checkout = $user->withCoupon($coupon->id)
->checkout($shirtPrice->id, [
'success_url' => 'http://example.com',
'cancel_url' => 'http://example.com',
]);
```
There's a minor breaking change in the sense that the `$coupon` and `$promotionCode` properties have been renamed to `$couponId` & `$promotionCodeId`. There's two reasons for that:
1. I wanted to prevent conflicting with a `coupon` column on the billable model
2. I wanted to more explicitly indicated that these …
> [13.x] Extract coupon functionality to trait

- src/Concerns/ManagesCustomer.php
- tests/Feature/CustomerTest.php
Small follow up on https://github.com/laravel/cashier-stripe/pull/1178. I figured it might also be prudent to sync all of this info when initially creating the customer.
> [13.x] Sync more upon creation

- CHANGELOG.md
- UPGRADE.md
- database/factories/SubscriptionItemFactory.php
- database/migrations/2019_05_03_000003_create_subscription_items_table.php
- src/Concerns/ManagesSubscriptions.php
- src/Http/Controllers/WebhookController.php
- src/Subscription.php
- src/SubscriptionBuilder.php
- src/SubscriptionItem.php
- tests/Feature/MultipriceSubscriptionsTest.php
- tests/Feature/SubscriptionsTest.php
- tests/Feature/WebhooksTest.php
Implements https://github.com/laravel/cashier-stripe/issues/1179
This adds a new `stripe_product`  column to the `subscription_items` table. This will open the door for new API's in Cashier Stripe like the `onProduct` and `subscribedToProduct` methods on a billable. There's potentially more extra methods to be added later on but these should provide support for the most common use cases already.
> [13.x] Implement `stripe_product` column

- .github/workflows/tests.yml
- CHANGELOG.md
- composer.json
Dropping this early on in the 14.x development cycle will reduce API calls to Stripe and avoid hitting their rate limiting more.
> [14.x] Drop PHP 7.3 support

- src/Billable.php
- src/Concerns/CalculatesTaxes.php
- src/Concerns/ManagesInvoices.php
- src/Concerns/PerformsCharges.php
- src/Subscription.php
- src/SubscriptionBuilder.php
This implements support for Stripe Tax into Cashier Stripe. 
```php
$subscription = Auth::user()->newSubscription('default', 'price_monthly')
->withTax()
->create('pm_card_visa');
```
Checkout:
```php
$checkout = Auth::user()
->withTax()
->checkout('price_tshirt');
```
Invoice:
```php
$invoice = Auth::user()
->withTax()
->invoiceFor('price_tshirt', 2000);
```
> [13.x] Implement support for Stripe Tax

- src/Billable.php
- src/Concerns/HandlesTaxes.php
- src/Concerns/PerformsCharges.php
- src/Subscription.php
- src/SubscriptionBuilder.php
This allows a Stripe Checkout session to collect a customer's Tax ID which can be used to calculate taxes, etc.
```php
$checkout = $user->collectTaxIds()->checkout('price_tshirt');
```
More info: https://stripe.com/docs/tax/checkout/tax-ids
Additionally, I've renamed the concerns trait to handle all tax things. It's unreleased yet so not a breaking change.
> [13.x] Collect Tax IDs in Checkout

- UPGRADE.md
Apps that upgrade should also update their webhooks to the same API version.
> [13.x] Note updating webhooks in upgrade guide

- config/cashier.php
- src/Cashier.php
- src/Concerns/HandlesTaxes.php
- src/Concerns/PerformsCharges.php
- src/Subscription.php
- src/SubscriptionBuilder.php
This implements a new `Cashier::calculateTaxes()` static method that'll allow you enable automatic tax calculation on all relevant Stripe calls. By default it follows Stripe's behavior and is set to `false`. Additionally, the previous `withTax` method is now deprecated as it is not needed anymore. You can now use your code as regularly without the need of using extra methods. This method call goes into the boot method of your `ApServiceProvider`.
Also, the `tax_id_collection` is now enabled by default when the calculation of taxes is enabled. This PR also fixes a typo for an forgotten rename of `collectsTaxIds`.
I'll send in a PR to the docs when this one is accepted.
> [13.x] Implement new calculateTaxes call

- src/Subscription.php
- src/SubscriptionItem.php
Fixes https://github.com/laravel/cashier-stripe/issues/1199
> [13.x] Use correct method visibility

- composer.json
- src/CashierServiceProvider.php
- src/Console/WebhookCommand.php
This implements a webhook command to easily set up the webhook needed to send the events that Cashier needs from Stripe. By default it'll use the `APP_URL` with the default webhook route and the default Cashier version. Both of these can be customized. You can also pass a `--disabled` flag if you don't want it to start sending events straight away.
```bash
php artisan cashier:webhook
php artisan cashier:webhook --url="http://example.com/stripe/webhook"
php artisan cashier:webhook --api_version="2019-12-03"
php artisan cashier:webhook --disabled
```
This will make the setup process that much easier for new Cashier users and users that are upgrading to newer versions. We can add this command to the upgrade guide.
> [12.x] Implement webhook command

- src/Concerns/HandlesTaxes.php
- src/Concerns/ManagesInvoices.php
- src/Concerns/PerformsCharges.php
This is a temporary implementation that prevents single charge methods from being used while automatic tax calculation is enabled. Until a better way to handle this is found this is the best solution to warn people about not using these two features together.
> [13.x] Prevent tax calculation for one-off charges

- UPGRADE.md
This PR is an attempt at explaining how you can upgrade to a new webhook with the correct Stripe API version. I hope it's detailed enough for people to know the exact steps they need to do to upgrade their webhooks.
> [13.x] Explain upgrading to a new webhook

- src/Concerns/ManagesInvoices.php
- src/Invoice.php
- tests/Feature/InvoicesTest.php
This PR changes the behavior of `->invoice()` to cascade Stripe exceptions. Previously they were silently failing by returning false. It's best to better inform the user when something goes amis or when they're attempting to invoice a user when there isn't anything to invoice. Most likely this means there's a mistake in their system so it's good to explicitly warn about that. `CardException`'s are still caught to trigger the `IncompletePayment` exceptions.
> [14.x] Cascade Stripe exceptions when invoicing

- src/Concerns/ManagesInvoices.php
- tests/Feature/InvoicesTest.php
Adds an `invoicePrice` and `tabPrice` method that works with a given Price ID. This is a useful alternative to single charge invoices which cannot be used in combination with automatic tax calculation.
```php
// Invoice for a single price...
$invoice = $user->invoicePrice('price_tshirt', 5);
// Invoice for a couple of prices
$user->tabPrice('price_tshirt', 5);
$user->tabPrice('price_mug', 5);
$invoice = $user->invoice();
```
Closes https://github.com/laravel/cashier-stripe/issues/1211
> [13.x] Add invoicePrice and tabPrice methods

- src/Concerns/ManagesCustomer.php
- src/CustomerBalanceTransaction.php
- src/Exceptions/InvalidCustomerBalanceTransaction.php
- tests/Feature/CustomerTest.php
This PR implements some API's around customer balances. This will make it easier for apps to retrieve a customer's balance, apply new balance transactions and display a history of balance adjustments.
```php
// Retrieve current balance...
$balance = $user->balance(); // $5.00
// Credit new balance...
$user->applyBalance(500, 'Premium customer top-up.');
// Debit balance...
$user->applyBalance(-300, 'Bad usage penalty.');
// Retrieve all transactions...
$transactions = $user->balanceTransactions();
// Display all transactions...
foreach ($transactions as $transaction) {
// Specific amount of the transaction...
$transaction->amount();
// Retrieve the related invoice when available...
$transaction->invoice();
}
```
Closes https://github.com/laravel/cashier-stripe/issues/762
> [13.x] Implement customer balances

- src/Concerns/ManagesInvoices.php
- src/Invoice.php
This was what I originally wanted to do for v13 but forgot 🤦‍♂️ 
There's no breaking changes (except to the method signatures). By default if no product key is provided, it'll use the app name to set the filename before the month/date.
> [14.x] Make invoice data optional

- src/Checkout.php
This PR implements some nice API's to Stripe's recent addition of exposing the Checkout url on its session object. This will greatly simplify the workflow for a library like Cashier to use redirects instead of doing it through Stripe.js
Before:
```php
$checkoutBtn = Auth::user()->checkout('price_tshirt')->button();
return view('checkout', compact('checkoutBtn'));
```
And have the customer click a button. Now:
```php
return Auth::user()->checkout('price_tshirt');
```
I've deprecated the `button` method because I think that from now on that's going to be a very rare use case.
> [13.x] Server side Checkout redirect

- resources/views/payment.blade.php
- src/Http/Controllers/PaymentController.php
When requires_action is presented on a card payment, the currently set payment method should be used to handle any extra action required by Stripe.
Fixes https://github.com/laravel/cashier-stripe/issues/1221
> [13.x] Fix issue with requires_action

- src/Http/Controllers/WebhookController.php
This PR fixes an async issue with webhooks. When using a checkout session, a susbcription created and subscription updated event are sent by Stripe. Because Stripe handles the checkout session so fast, these are sent at almost the exact same time. This can cause the updated event to arrive before the created event. By delaying the updating event by one second, we give ample time for the created webhook to be handled first. This solution was suggested by a community member who tried it out in their production app and hasn't experienced the issue ever since.
Fixes #1201
> [13.x] Fix async issue with webhooks

- src/Concerns/ManagesInvoices.php
- src/Subscription.php
- src/SubscriptionBuilder.php
- tests/Feature/InvoicesTest.php
- tests/Feature/SubscriptionsTest.php
Stripe allows to create subscriptions and invoices without creating a `price` object via the dashboard beforehand. This is useful in cases where you want to create very individual subscriptions or invoices.
This PR adds the possibility to subscribe, swap and invoice with custom `price_data`:
```php
// Create Subscription
$user->newSubscription('main')->price([
'price_data' => [
'product'      => $productId,
'tax_behavior' => 'exclusive',
'currency'     => 'USD',
'recurring'    => [
'interval' => 'month',
],
'unit_amount'  => 1100
]
])
->create('pm_card_visa');
```
```php
// Create Invoice
$user->invoiceFor('Laravel T-shirt', 599, [
'price_data' => [
'product'      => $productId,
'tax_behavior' => 'exclusive'
]
]);
```
```php
// Swap Subscription
$subscription->swap([
[
'price_data' => [ …
```
> Add support for inline price data

- src/Subscription.php
- src/SubscriptionItem.php
Even though zero shouldn't be passed as a value for quantity it atm leads to an issue where Stripe will use one as a default and the database will be populated by zero. By using the value returned from the Stripe API call we make sure we always use the correct quantity that's set within Stripe.
Fixes #1237
> [13.x] Fix quantity filling on subscriptions

- src/Concerns/ManagesInvoices.php
- src/Subscription.php
This PR adds some new invoices methods to the Subscription model to retrieve invoices specific to that subscription. It uses the same API as the methods on the billable model.
```php
$invoices = $user->subscription()->invoices();
```
> [13.x] Add invoices methods to subscription

- database/migrations/2019_05_03_000002_create_subscriptions_table.php
- database/migrations/2019_05_03_000003_create_subscription_items_table.php
- src/Http/Controllers/WebhookController.php
- tests/Feature/MultipriceSubscriptionsTest.php
- tests/Feature/SubscriptionsTest.php
- tests/Feature/WebhooksTest.php
This PR is an attempt at fixing the issue with the subscripion.updated webhook arriving sooner than the subscription.created webhook. What we'll do is create the subscription when it isn't yet created. This is a more safer way than delaying the handling by one second.
Should the susbcription.created webhook be handled later on, it won't be created twice since there's a check in the subscription.created handler.
I've also added two new unique indexes on stripe_id columns in the subscription tables. Honestly I don't know why these weren't there before.
I've tried this out and manages to confirm it fixes things for me in the situation that the subscription.updated webhook arrives first.
PS.: most of the changes in this PR are indentation changes.
> [13.x] Fix webhook order issue

- src/Concerns/ManagesInvoices.php
- src/Invoice.php
This fixes a bug where an upcoming invoice is refreshed but its original parameters weren't sent along. For example, a previewed invoice wouldn't look the same in its PDF download.
> [13.x] Send data when upcoming invoice is refreshed

- src/Concerns/PerformsCharges.php
When enabling tax id collection, Stripe will throw an exception when you don't explicitly enable customer name and billing address updates.
> [13.x] Update customer details when tax id is collected

- database/factories/SubscriptionFactory.php
Probably better to use a default name here. When they need other subscriptions in their tests they can use specific names as I suspect everyone is already doing.
> [13.x] Use default name for subscription factory

- src/Subscription.php
Subscription items with a metered price don't have a quantity.
Fixes https://github.com/laravel/cashier-stripe/issues/1254
> [13.x] Fallback to null quantity for metered price

- src/SubscriptionBuilder.php
This fixes a Stripe Notice (Stripe Notice: Undefined property of Stripe\SubscriptionItem instance: quantity) when using the SubscriptionBuilder with metered prices.
See my comments on #1254.
> [13.x] Fix a stripe notice with SubscriptionBuilder and metered prices

- src/Cashier.php
This PR allows the base url of the Stripe API to be changed if needed, such as when using https://github.com/stripe/stripe-mock.
If there's already a way to change the base url without needing this change then please let me know what I'm missing as I couldn't see a way to customise the `$options` parameter of the `stripe()` method.
> Allow the base url for the Stripe API to be customised

- tests/Feature/FeatureTestCase.php
- tests/Feature/MeteredBillingTest.php
- tests/Feature/MultipriceSubscriptionsTest.php
- tests/Feature/PendingUpdatesTest.php
- tests/Feature/SubscriptionsTest.php
- tests/Feature/WebhooksTest.php
This will allow PR's to pass their test suite when submitted. Of course, we'll still only notice breakages after merging. Ideally, Stripe will provide tooling for us in the future to mock their API.
> [13.x] Skip tests without Stripe Secret

- database/factories/SubscriptionFactory.php
This PR fixes an invalid state for the cancelled status. A cancelled status in Cashier also needs it ends_at timestamp filled in.
Fixes #1278
> [13.x] Fix factory canceled state

- CHANGELOG.md
- UPGRADE.md
- resources/views/payment.blade.php
- src/Http/Controllers/WebhookController.php
- src/Payment.php
- src/Subscription.php
- tests/Feature/SubscriptionsTest.php
- tests/Feature/WebhooksTest.php
- tests/Unit/PaymentTest.php
Stripe maintains the American "canceled" while we in Cashier use the British "cancelled". I believe bringing this on-par with Stripe will be easier to make the translation between Cashier/Stripe.
Old methods have been aliased so there are no breaking changes. Good thinking @taylorotwell 👍 
Replaces https://github.com/laravel/cashier-stripe/pull/1281
> [13.x] Rename cancelled to canceled

- .github/workflows/tests.yml
- composer.json
This is a breaking change for some users, as moneyphp version 4 requires the bcmath extension
> [13.x] Allow latest moneyphp version

- composer.json
Although my reasoning in https://github.com/laravel/cashier-stripe/pull/1280 was correct, we in fact don't need to do this directly in Cashier because `moneyphp/money` will already require this.
> [13.x] Remove bcmath extension

- src/Concerns/ManagesPaymentMethods.php
- src/PaymentMethod.php
- tests/Feature/PaymentMethodsTest.php
> [13.x] Add deletePaymentMethod

- src/SubscriptionBuilder.php
In some edge cases, the webhook that handles the subscription creation arrives before we can insert the record into the database with the subscription builder. Therefor, we should check if it's already in the database and if so, return it.
Fixes #1307
> [13.x] Prevent duplicate subscription creation

- composer.json
This makes dompdf an optional dependency. Now that we have decoupled it behind an interface it can be an optional dependency. And if people want to use their own renderers they can choose not to install it: https://github.com/laravel/cashier-stripe/issues/1311
> [14.x] Make dompdf optional

- .github/CONTRIBUTING.md
- src/Http/Controllers/WebhookController.php
- src/Http/Middleware/VerifyRedirectUrl.php
- tests/TestCase.php
Improve https://github.com/laravel/cashier-stripe/pull/1314 a bit by using the config helper instead. Also add some extra safeguarding in the contribution docs.
PS.: I also had to push a fix for the redirect url middleware that was suddenly failing on PHP 8.1
> [13.x] Improve test key check

- src/SubscriptionBuilder.php
- tests/Unit/SubscriptionBuilderTest.php
> [13.x] Allow normal and metered prices in builder

- src/Cashier.php
This will allow an underlying library to use the given locale in a custom formatter.
> [13.x] Pass locale to custom format amount

- .github/workflows/tests.yml
- src/Coupon.php
- src/CustomerBalanceTransaction.php
- src/Discount.php
- src/InvoiceLineItem.php
By enabling deprecation throwing in tests, we can solve them early-on.
> [13.x] Throw deprecations in tests

- .github/workflows/tests.yml
- UPGRADE.md
- composer.json
Drop support for old PHP and Laravel versions for the next major release.
> [14.x] Drop PHP 7.4 and Laravel v8 support

- resources/views/receipt.blade.php
This PR fixes a deprecation in Cashier Stripe with Carbon.
See #1355
> [13.x] Fix deprecation with Carbon on receipts

- src/Concerns/AllowsCoupons.php
- src/Concerns/ManagesCustomer.php
- src/Discount.php
- src/PromotionCode.php
- src/Subscription.php
- tests/Feature/DiscountTest.php
- tests/Feature/SubscriptionsTest.php
This PR implements some improvements and new API's for discount handling.
First of all, a new `PromotionCode` class was added that wraps a `Stripe\PromotionCode` object. This object represents a promotion code applied to either a customer or subscription. 
Further, the `Discount` class now also features a `promotionCode` method to easily retrieve the promotion code should one have been used to apply a discount. Besides that, the class got dedicated methods to transform the `start` and `end` timestamps of a discount into `Carbon\Carbon` objects.
Other than that it's now easy to retrieve a `PromotionCode` by its code:
```php
// Find the promotion code with 25OFF...
$promotionCode = $billable->findPromotionCode('25OFF');
// Or find only active promotion codes...
$promotionCode = …
```
> [13.x] Discount improvements

- src/Http/Controllers/WebhookController.php
This should reference the billable rather than the Cashier class.
> [13.x] Fix reference to billable

- src/Concerns/ManagesSubscriptions.php
- src/Subscription.php
- tests/Unit/CustomerTest.php
- tests/Unit/SubscriptionTest.php
Currently, there isn't a convenient way to check if a trial period has expired. We can't simply wo `! $user->onTrial()` because it could be that the user didn't have a trial to begin with.
To, for example, display a banner that a billable's trial has expired we need to know that they were trialing in the first place and that the period has expired.
Closes https://github.com/laravel/cashier-stripe/issues/1361
> [13.x] Add new hasTrialExpired methods

- src/Subscription.php
- src/SubscriptionBuilder.php
Fixed `Stripe Notice: Undefined property of Stripe\SubscriptionItem instance: quantity` when creating or swapping to a single metered price.
Related: #1254 
Test:
```
cashier-stripe % ./vendor/bin/phpunit --filter test_swap_metered_price_to_different_price
PHPUnit 9.5.20
Stripe Notice: Undefined property of Stripe\SubscriptionItem instance: quantity
Stripe Notice: Undefined property of Stripe\SubscriptionItem instance: quantity
.Stripe Notice: Undefined property of Stripe\SubscriptionItem instance: quantity
Stripe Notice: Undefined property of Stripe\SubscriptionItem instance: quantity
.                                                                  2 / 2 (100%)
Time: 00:23.421, Memory: 28.00 MB
OK (2 tests, 24 assertions)
```
> Fixed undefined quantity notice

- UPGRADE.md
- src/Concerns/ManagesPaymentMethods.php
- tests/Feature/PaymentMethodsTest.php
This PR reverts the changes made in https://github.com/laravel/cashier-stripe/pull/1077. Because Stripe underneath still uses the Sources API themselves in some situations (adding a card through the dashboard, using the hosted payment page, ...) cards, etc get added as a `default_source`. This is unfortunate but the best course to proceed is to simply continuing to sync the default source Stripe sets and return it when it's available. This will provide the least friction to users.
We should still encourage people to not use the Sources API themselves like we do here: https://github.com/laravel/docs/pull/7997
Also see https://github.com/laravel/cashier-stripe/issues/1310
> [13.x] Re-add support for Sources API

- resources/views/receipt.blade.php
- src/Invoice.php
- tests/Unit/InvoiceTest.php
This PR fixes receipt totals when a balance is applied. 
Here's an example with the current Cashier receipt:
And here's the Stripe invoice:
As you can see these numbers do not match. There's no reason the total customer balance should be displayed and the final total invoice amount isn't correct (should be €12.10). 
With this PR it gets fixed to:
So it's the same as the Stripe one. I've added new methods to the Invoice object to accommodate for these changes.
There's one note I'd like to make: the current behavior of the Invoice's `total` method is actually incorrect. I've added a new `realTotal` method to temporarily accommodate for the true value. I did not want to break backwards compatibility which is why I opted for a new method. In Cashier v14, I strongly want to urge to change the …
> [13.x] Fix receipt totals and balance

- composer.json
This is to add the change from #1391 to the `13.x` branch. The last version of domdpf v1 has a [security vulnerability](https://github.com/advisories/GHSA-pf6p-25r2-fx45) and it doesn't look like they intend to patch v1.
> [13.x] Allow dompdf v2

- src/Checkout.php
In Cashier v14 I'd like to make a change to the default payment methods used on a Checkout session by allowing to manage them from the Dashboard by default. Removing this parameter will allow vendors to turn off and on payment methods from the dashboard as they please.
See https://stripe.com/docs/payments/dashboard-payment-methods#update
Closes https://github.com/laravel/cashier-stripe/issues/1379
> [14.x] Manage Checkout PM from Dashboard

- composer.json
- src/Console/WebhookCommand.php
This pull request improves the console output.
> [14.x] Improves console output

- src/Concerns/ManagesInvoices.php
- src/Invoice.php
- tests/Feature/InvoicesTest.php
This PR adds some new functionality to Cashier to allow to create invoices separately without sending them (draft state) as well as a few methods to add new items to invoices directly.
```php
// Creates a new empty draft invoice...
$invoice = $user->createInvoice();
// Add a new price line item to the invoice...
$invoice->tabPrice('price_xxx', 5);
```
Closes https://github.com/laravel/cashier-stripe/issues/1397
> [13.x] Create invoices separately

- src/Concerns/ManagesCustomer.php
This PR adds an easy way to sync preferred locales for customers. By providing this, customers will be able to set their preferred locales so their Stripe receipts are translated as well. 
Targeting master because now that this is part of `syncStripeCustomerDetails` it could reset customer's value with the new default value. We'll note this in the upgrade guide.
Closes https://github.com/laravel/cashier-stripe/issues/1399
> [14.x] Sync preferred locales

- src/Concerns/ManagesInvoices.php
The `pending_invoice_items_behavior` behavior should be overwritable if the app intends that.
> [13.x] Fix issue with overwriting behavior

- composer.json
At first glance on the changelog, there don't seem to be breaking changes to Cashier v13 or Spark v2.
https://github.com/stripe/stripe-php/blob/master/CHANGELOG.md
> [13.x] Allow Stripe SDK v9

- src/Cashier.php
- src/Concerns/ManagesInvoices.php
- tests/Feature/InvoicesTest.php
This PR bumps the Stripe API version to the latest 2022-08-01 version: https://stripe.com/docs/upgrades#2022-08-01
The most notable breaking change is that no exception will be thrown anymore when an invoice is attempted to be made while there are no pending invoice items. Instead, a new draft invoice will be created.
> [14.x] Update to new Stripe version

- src/Concerns/HandlesPaymentFailures.php
- src/Concerns/InteractsWithPaymentBehavior.php
- src/Subscription.php
- src/SubscriptionBuilder.php
- src/SubscriptionItem.php
This PR adopts the new recommended `default_incomplete` payment behavior that Stripe now recommends. The main adjustments here are the transition to the new `default_incomplete` value when passing the `payment_behavior` when creating or updating subscriptions or subscription items and confirming the payment intents server-side before throwing the `IncompletePayment` exception.
I've extracted the logic to handle payment failures in a new `HandlesPaymentFailures` trait. In here, we'll check if a subscription has a failed payment. If so, we'll check if it needs confirmation and when it does we'll confirm it server-side. If a payment method has been provided as well (usually when creating a subscription) we'll pass it along. After confirming the payment we'll need to update the subscription …
> [14.x] New subscription behavior

- UPGRADE.md
- src/Concerns/ManagesCustomer.php
- src/Concerns/ManagesInvoices.php
- src/Subscription.php
This PR also contains a slight change to `stripePreferredLocales` so it returns `null` and doesn't syncs the locale so it's completely BC. Removed a couple of old return types as well for the invoice methods.
> Upgrade Guide v14

- resources/views/receipt.blade.php
Only show the applied balance when there is any. Otherwise it doesn't really has any meaning.
> [13.x] Fix applied balance on receipts

- src/Console/WebhookCommand.php
I realized this webhook isn't added when you update Spark to the latest version. Instead of writing docs so people can add this manually I think it's easier to just add the event to the Cashier webhook even if Cashier itself doesn't handles the event (but Spark does). I'll merge upstream into v14.
> [13.x] Add invoice.payment_succeeded event to WebhookCommand

- resources/views/receipt.blade.php
- src/InvoiceLineItem.php
This fixes #1431, following the stripe "when are dates shown" on invoices as per https://stripe.com/docs/api/invoiceitems/object#invoiceitem_object-period
> [14.x] Renders the invoice item dates on invoices when set

- src/Concerns/ManagesInvoices.php
- tests/Feature/SubscriptionsTest.php
Apparently you cannot combine the `pending_invoice_items_behavior` and `subscription` parameters when invoicing a subscription directly. Added a test to check for this.
Fixes https://github.com/laravel/cashier-stripe/issues/1433
> [14.x] Fix subscription invoicing bug

- config/cashier.php
- src/Console/WebhookCommand.php
This will allow adding more enabled webhook events when creating a stripe webhook using `php artisan cashier:webhook`
> [14.x] Configurable Webhook Enabled Events

- src/Concerns/ManagesSubscriptions.php
- tests/Feature/CustomerTest.php
This pull requests adds two scopes to the Billable model to scope by the generic trial state. These scopes are similar to those introduced in https://github.com/laravel/cashier-stripe/pull/609.
It allows you to grab any Billable that is on, or has had a generic trial.
```php
$onGenericTrial = Customer::query()->onGenericTrial()->get();
$hasExpiredGenericTrial = Customer::query()->hasExpiredGenericTrial()->get();
```
> [14.x] Add generic trial scopes

- src/SubscriptionBuilder.php
- tests/Feature/SubscriptionsTest.php
This PR adds the `days_until_due` to the `createAndSendInvoice` method since it's apparently required for the `sends_invoice` value of `collection_method`. A sensible default seemed 30 to me like in the Stripe docs: https://stripe.com/docs/invoicing/integration/quickstart
> [14.x] Add days until due to sends invoice

- src/Checkout.php
- src/CheckoutBuilder.php
- src/Concerns/AllowsCoupons.php
- src/Concerns/HandlesTaxes.php
- src/Concerns/PerformsCharges.php
- src/SubscriptionBuilder.php
- tests/Feature/CheckoutTest.php
These changes are a followup to the guest checkout PR here: https://github.com/laravel/cashier-stripe/pull/1438. These allow for a more richer Checkout experience and a more fluent one. You can now use any method from the `AllowsCoupons` and `HandlesTaxes` traits:
```php
$checkout = Checkout::guest()
->withCoupon('coupon_id')
->withTaxAddress('US', '72201', 'Arkansas')
->create();
```
Furthermore, I've managed to bring all of resolving of the Checkout Session options into the new `CheckoutBuilder` class which will help in the future when adding new features to the Cashier Stripe Checkout experience.
One thing I needed to change are the property visibilities on the `AllowsCoupons` and `HandlesTaxes` traits so I could more easily copy them over.
A future change I'd like to make is to move …
> [14.x] Improve guest Checkout flow

- resources/views/receipt.blade.php
- src/Invoice.php
- tests/Unit/InvoiceTest.php
This PR fixes a small issue I ran into when a balance is applied to an invoice but not shown on the receipt.
> [14.x] Fix applied balance on invoices

- src/InvoiceLineItem.php
I updated my installation of Cashier to `v14.2.0` and noticed that my invoices can't be downloaded. Did some digging around and found that the newly added `unitAmountExcludingTax` method in the `InvoiceLineItem` class doesn't handle `null` values coming through from the Stripe PHP library. This pull request aims to fix the issue by setting `null` values to `0` (int), this will ensure that values passed to `Cashier::formatAmount()` is always a `int` or `string` type.
For some context around why I am likely to get a `null` value. My application charges a fixed price per `website` and a fixed price per `user` (team members). This means that a `team` in my application can possibly have `0` websites but always have 1 or more users, this would mean their subscription would still be active but …
> [14.x] Add fallback for null value in unitAmountExcludingTax method

- src/Invoice.php
Fix `PHP message: Stripe Notice: Undefined property of Stripe\Invoice instance: id` when fetching upcoming invoice data
> Fix undefined property id notice

- src/Invoice.php
StripeObject saves the value to the array, not a property. This PR also fixes tests.
https://github.com/stripe/stripe-php/blob/e73d05039943e3bbcd0f068f220ee55f88e8952c/lib/StripeObject.php#L152-L160
test result:
> Fix StripeObject values problem

- src/Subscription.php
Removes the dates property from the subscriptions model since it's deprecated. Only the ends_at and trial_ends_at attributes are added as casts since created_at and updated_at are already properly handled.
> [14.x] Refactor dates property

- src/Cashier.php
- src/Subscription.php
This PR allows subscriptions to stay active as long as they're in an `incomplete` status. The reason for this is that it could be that subscriptions are pending on SCA confirmation etc. During this window, customers could miss out on any access to the product they're using. In normal situations, that's what you want since at this point, they're not paying for the product. However, often this can be disruptive as well to the customer experience. Therefor allowing apps to keep these incomplete subscriptions as active is a valid option to provide. Works exactly the same as `keepPastDueSubscriptionsActive`.
The default behavior is unchanged as it should be. As soon as a subscription hits `incomplete_expired` the subscription is no longer active. …
> [14.x] Allow incomplete subscriptions as active

- src/InvoiceLineItem.php
When i try:
`$user->downloadInvoice($invoiceId);`
I receive the following exception:
```
production.ERROR: Attempt to read property "percentage" on string (View: /var/app/current/vendor/laravel/cashier/resources/views/receipt.blade.php) {"exception":"[object] (Illuminate\\View\\ViewException(code: 0): Attempt to read property \"percentage\" on string (View: /var/app/current/vendor/laravel/cashier/resources/views/receipt.blade.php) at /var/app/current/vendor/laravel/cashier/src/InvoiceLineItem.php:146)
[stacktrace]
#0 /var/app/current/vendor/livewire/livewire/src/ComponentConcerns/RendersLivewireComponents.php(106): Illuminate\\View\\Engines\\CompilerEngine->handleViewException(Object(ErrorException), 1)
#1 /var/app/current/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php( …
```
> Exception Attempt to read property "percentage" on string

- UPGRADE.md
- composer.json
- src/Cashier.php
Usually updating the Stripe API version is done in major releases of Cashier. But since the changes are minimal here I think it's safe to do them in a minor release this time.
> [14.x] Update Stripe API version and Stripe PHP SDK v10 support

- composer.json
- src/Concerns/ManagesInvoices.php
This PR adds cursor pagination for customer invoices. Using the `starting_after` and `ending_before` fields on [the invoices list API endpoint](https://stripe.com/docs/api/invoices/list) by Stripe, we can easily paginate through a customer's invoices using cursors.
```php
$paginator = $billable->cursorPaginateInvoices();
```
> [14.x] Cursor pagination for invoices

- src/SubscriptionItem.php
This pull request fixes an error in the relationship between **items** and **subscription** when using _custom models_ 
i.e. using 
```
Cashier::useSubscriptionModel(StripeSubscription::class);
Cashier::useSubscriptionItemModel(StripeSubscriptionItem::class);
```
With these I think "licit" migrations
```
Schema::create('stripe_subscriptions', function (Blueprint $table) {
$table->id();
....
});
Schema::create('stripe_subscription_items', function (Blueprint $table) {
$table->id();
$table->foreignId('stripe_subscription_id');
...
});
```
current codebase works in finding the items from the subscription, but not in finding the subscription from the items.
so $item->subscription will never works without this fix.
Of course, it can be solved by overriding the relation in our custom …
> [14.x] Fix wrong foreignKey on SubscriptionItem

- src/Concerns/ManagesCustomer.php
In some cases, people might not have a phone, email or name attribute. In those cases we should return `null` by default.
> [14.x] Return null if attribute isn't found

- tests/Feature/FeatureTestCase.php
Trying this to remedy the nightly failures we've been experiencing for the past month.
> Disable HTTP 2 in tests

- src/Invoice.php
This PR ensures all line items are shown on a invoice, even the ones with lots of them (+10). This is a workaround for a bug in Stripe atm with their auto paginator: https://github.com/stripe/stripe-php/issues/1422
> [14.x] Fix invoice line items

- src/Concerns/ManagesPaymentMethods.php
- tests/Feature/PaymentMethodsTest.php
The new Payment element requires a redirect to a new page after submitting the payment details, to enable the insertion of intermediate paymentMethod steps (for example bank pages etc.)
When the return_url is reaches, the setupIntent is supplied as a parameter, with the purpose of allowing the code to retrieve the setupIntent, to get the payment_method id.
This PR provides a findSetupIntent method on the billable entity, to enable retrieval of the setupIntent.
Test included.
This is described by @quantumwebco in issue https://github.com/laravel/cashier-stripe/issues/1491
fixes https://github.com/laravel/cashier-stripe/issues/1491
> [14.x] Provide findSetupIntent method

- src/Subscription.php
This pull request fixes an issue in `Subscription::swap()` where subscription item models created using inline prices (via `price_data`) instead of an existing Stripe price are immediately deleted after creation:
```php
// Delete items that aren't attached to the subscription anymore...
$this->items()->whereNotIn('stripe_price', $items->pluck('price')->filter())->delete();
```
Items using inline price data will not be keyed by `price` in `parseSwapPrices()`, meaning they will not be found by `$items->pluck('price')`. This change simply uses the item data returned by the updated Stripe subscription object as the source of truth instead of the array that is initially passed to `swap()`. FWIW, I considered adding post-creation/swapping item relation counts to the feature tests relating to …
> [14.x] Fix deletion of subscription items in swap()

- src/Concerns/HandlesPaymentFailures.php
Right now, it's not possible to create subscriptions without also automatically confirming them. It would be handy for apps where the frontend like Next.js etc handles the confirmation through Stripe.js for example without providing a payment method up front.
```php
$subscription = $user->newSubscription('default', 'price_xxx')
->ignoreIncompletePayment()
->create();
```
I'm not 100% sure about the naming of `ignoreIncompletePayment` yet.
> [14.x] Add ability to ignore incomplete payments

- src/Concerns/PerformsCharges.php
Right now its not possible to set a description for checkout sessions created with for example
```
$request->user()->checkoutCharge(1200, 'T-Shirt', 5);
```
> [14.x] Add ability to set a description on "one-off" charge checkouts

- src/Invoice.php
This PR removes the `isDeleted` method from the invoice object because the status doesn't exists anymore in Stripe.
> [15.x] Remove isDeleted method

- src/Concerns/ManagesPaymentMethods.php
This should fix issue https://github.com/laravel/cashier-stripe/issues/1530 by falling back to null for the `last4` attribute when it is not accessible on certain payment method types including `cashapp`, allowing support for Cash App Pay.
> [14.x] Fallback for empty pm_type object on fillPaymentMethodDetails

- UPGRADE.md
- src/Console/WebhookCommand.php
- src/Http/Controllers/WebhookController.php
Vendors, including Visa and Mastercard, often reissue and update stored payment methods in place for Stripe users. This can involve updating the expiration date, but frequently also changes the entire card number as well.
The [Stripe events log](https://dashboard.stripe.com/events?type=payment_method.automatically_updated) filtered for this type of event shows how often it happens, which we are seeing several times per day in our own apps (more than I would have expected).
These automatic updates allow the payment methods to continue to be successfully charged by Stripe, but has the side effect of causing the Cashier user model to become out of sync with the outdated `pm_last_four` stored.
Fortunately, Stripe sends a `payment_method.automatically_updated` webhook when this happens that …
> [14.x] Handle automatic payment method updates

- src/Checkout.php
This fixes a bug where sometimes, `customer_update` was being set even though no customer was provided. This change will fix that behaviour by only including the option when a customer is set.
Fixes https://github.com/laravel/cashier-stripe/issues/1537
> [14.x] Fix bug with customer_update in checkout

- src/Concerns/ManagesCustomer.php
Our `User` model has the `Billable` trait applied to it. In order to make it easier to search Stripe for the correct user, we've been syncing the user ID in the metadata. I've noticed this has lead to a decent amount of code duplication.
```php
class User extends Model
{
public function refreshStripeData()
{
$options = [
'metadata' => [
'user_id' => $this->id,
],
];
if ($this->hasStripeId()) {
$this->syncStripeCustomerDetails($options);
} else {
$this->createAsStripeCustomer($options);
}
$this->updateDefaultPaymentMethodFromStripe();
}
public function ensureStripeUserExists()
{
if (!$this->hasStripeId()) {
$this->createAsStripeCustomer([
'metadata' => [
'user_id' => $this->id,
],
]);
}
}
}
```
This also means that if someone else is writing code that creates/syncs users in Stripe, they …
> Update ManagesCustomer to include optional metadata when creating or syncing a user

- src/Concerns/ManagesPaymentMethods.php
Similarly to the creation of a `PaymentIntent` using the `$user->pay()` method, the `$user->createSetupIntent()` method should also create a `SetupIntent` attached to the user's Stripe Customer if it exists.
Otherwise, all Setup Intents are created as Stripe guest customers.
So this PR makes both methods for creating intents behave the same way.
> createSetupIntent add customer stripe_id option

- src/Subscription.php
Breaking change PR in 14.x moved to 15.x (master)
Added expand option to latestInvoice() method so you can get the payment intent to check for 3DS requires action
When using $invoice->pay() it does not throw an Cashier IncompletePayment exception it throws a native Stripe CardException so the payment intent is not in the error object, it helps to have the payment intent on the invoice so you can check before attempting to pay()
> Added expand option to Subscription latestInvoice()

- src/Concerns/ManagesCustomer.php
- src/Concerns/ManagesInvoices.php
- src/Concerns/ManagesPaymentMethods.php
- src/Concerns/PerformsCharges.php
This pull request
💁‍♂️ For reference, see
https://github.com/laravel/cashier-stripe/blob/635f8b81cacdcc963dc55d124916a8a65553f639/src/Concerns/ManagesCustomer.php#L553-L556
> Fix: Invoke `static` method statically

- tests/Unit/InvoiceTest.php
This pull request
Somewhat related to #1556.
> Fix: Add tests for `Invoice::isDeleted()`

- .github/CONTRIBUTING.md
This pull request
Replaces #1562.
💁‍♂️ Running
```shell
git grep CASHIER_MODEL
```
on current `14x.` yields
```
.github/CONTRIBUTING.md:9:Copy the default file using `cp phpunit.xml.dist phpunit.xml` and add the following line below the `CASHIER_MODEL` environment variable in your new `phpunit.xml` file:
UPGRADE.md:584:The `STRIPE_MODEL` environment variable has been renamed to `CASHIER_MODEL`.
```
so it does not exist in `phpunit.xml.dist`.
> Fix: Remove reference to `CASHIER_MODEL` enviromment variable

- src/Concerns/ManagesCustomer.php
When your Billable does not overload stripeMetadata() and a billable is synced, any existing metadata on the Stripe customer is lost. 
The default behavior should be to preserve the existing metadata -- an empty array will accomplish this.
Deleting existing Stripe customer metadata is potentially devastating if you're using Stripe as a store for data that isn't persisted to your billable model.
> Prevent Sync From Deleting Existing Metadata

- src/SubscriptionBuilder.php
Example code:
```php
return $tenant->newSubscription($plan, $priceId)
->allowPromotionCodes()
->when($trailDays, fn (SubscriptionBuilder $builder) => $builder->trialUntil(Carbon::now()->endOfDay()->addDays($trialDays)))
->collectTaxIds()
->checkout([
'success_url' => Dashboard::getUrl(),
'cancel_url' => Dashboard::getUrl(),
])
->redirect();
```
> Add `Conditionable` trait to subscription builder

- src/SubscriptionBuilder.php
Makes sure the payload for checkout is recursively merged instead of overwritten. The `create` method of the builder doesn't suffers from this because the default payload doesn't have multidimensional options.
Fixes https://github.com/laravel/cashier-stripe/issues/1578
> [14.x] Fix array merge for checkout

- src/Concerns/ManagesCustomer.php
Returning an empty array instead of a `null` value will keep existing data from being overwritten.
> [14.x] Fix default sync

- src/Exceptions/InvalidPaymentMethod.php
- src/PaymentMethod.php
Uncover more info about why a payment method couldn't be instantiated.
> [14.x] Log more info about invalid pm exception

- src/Checkout.php
- src/CheckoutBuilder.php
Closes #1585 
This PR resolves an issue that appears to have been introduced from a Stripe 2023-10-16 API update, where only the existence of the `tax_id_collection.enabled` parameter requires the addition of the `customer_update` parameters, rather than being able to set it to `false` as it was previously, resulting in the exception:
```
Stripe\Exception\InvalidRequestException
Tax ID collection requires updating business name on the customer. To enable tax ID collection for an existing customer, please set `customer_update[name]` to `auto`.
```
The `tax_id_collection` collection parameter will now be completely omitted when auto-calculation of taxes is disabled.
> Bug 1585 - Tax ID collection requires updating business name on the customer

- database/migrations/2019_05_03_000003_create_subscription_items_table.php
I stumbled upon an edge case where Stripe created a new subscription item for the same price ID. This means Cashier attempts to insert this while the unique constraint is active. Although it's unlikely this happens often (we only saw this just a couple of times) we shouldn't rely on this index anymore.
> [14.x] Remove unique index from items table

- src/Payment.php
I am suggesting here a method very similar to `capture()` but for `cancel()`.
It simply call the `cancel()` method on the associated `PaymentIntent`.
> Add support for Payment cancelation

- src/Subscription.php
Do not perform an API request when retrieving the upcoming invoice of a canceled subscription.
> Early return upcoming invoice

- src/Checkout.php
- src/Http/Controllers/WebhookController.php
This will prevent confirmation emails from being sent when the customer is on-session in a Stripe Checkout.
> [14.x] Prevent confirm email when in Checkout

- src/Checkout.php
- tests/Feature/CheckoutTest.php
It is currently not possible to create embedded checkouts with cashier-stripe (see  #1590). Creating such a checkout requires a parameter `ui_mode` to be set to `embedded`.
This fails, because Stripe does not accept a `success_url` or `cancel_url` in this mode. Since these are added by the `Checkout` class on every creation, there is no way of preventing these parameters from being sent to Stripe and causing an error.
My minimal solution only adds `success_url` and `cancel_url` if `ui_mode` is not explicitly set to `embedded`, otherwise it enforces the existence of the `return_url` parameter.
A limitation of this solution is, that if the user explicitly set the `success_url` or `cancel_url` and is using the embedded mode, an error by Stripe will still appear, since these values are not …
> [14.x] Allow creation of checkouts with ui_mode=embedded

- resources/views/invoice.blade.php
- src/Invoice.php
This is something I've wanted to do for a long time already and that's to get rid of the last mention of "receipt" in Cashier Stripe. Stripe itself only uses "invoices" in their API's and that's what these documents are actually. Receipts is only a term used for a copy you get on Stripe emails but isn't the exact thing that's stored in Stripe. By consolidating this as "Invoice" we have a better presentation of these objects and documents.
Later on we can also adjust Spark Stripe for this. The migration path for this would be for people to rename their published view from `receipt.blade.php` to `invoice.blade.php`.
> [15.x] Rename receipt to invoice

- UPGRADE.md
- composer.json
- src/Cashier.php
- src/CashierServiceProvider.php
- testbench.yaml
- tests/Feature/FeatureTestCase.php
- tests/TestCase.php
This pull request makes cashier stops using `loadMigrationsFrom` on the next major version. Laravel 11 support will be shipped after 15.x is out, as regular minor version.
> [15.x] Stops using `loadMigrationsFrom`

- composer.json
- src/Cashier.php
- src/Concerns/ManagesInvoices.php
- src/Concerns/PerformsCharges.php
- src/Invoice.php
- tests/Feature/ChargesTest.php
This updates the Stripe API to the most recent one `2023-10-16` as well as update the SDK version to v13 which is compatible with it.
I also decided to drop support for older SDK versions because v13 is the one that's compatible with this API version.
Closes #1556
> [15.x] Stripe API and SDK update

- src/Concerns/ManagesPaymentMethods.php
Closed https://github.com/laravel/cashier-stripe/issues/1569
This PR changes the behaviour of the payment methods to fetch all payment method types, not just card ones. Previously, the Stripe API didn't allow you to do this and we were forced to always filter by a certain type so we chose "card" as a default as it's the most common one. But now we can offer a single way to fetch all payment methods for a customer in one go. This is useful for people to list these and not having to do multiple calls anymore to fetch each type separately.
> [15.x] Fetch all payment methods

- database/factories/SubscriptionFactory.php
- database/migrations/2019_05_03_000002_create_subscriptions_table.php
- src/Concerns/ManagesSubscriptions.php
- src/Concerns/PerformsCharges.php
- src/Http/Controllers/WebhookController.php
- src/SubscriptionBuilder.php
- tests/Feature/SubscriptionsTest.php
- tests/Feature/SubscriptionsWithMultiplePricesTest.php
- tests/Feature/WebhooksTest.php
I know this PR is opinionated but hope it can be considered. Right now, we regularly get issues about people being confused about this column's actual usage. People seem to be using this column as user-readable representation of the subscription product ("Gym Subscription") rather than what it actual is: a single internal subscription type (`gym`).
I've already patched Cashier Paddle v2 with this change and would like to make the same one in Cashier Stripe. This will require a single DB migration on the user's end to rename the column.
I know we try to avoid breaking changes but I think this one will be beneficial as it more closely indicates this column's purpose.
> [15.x] Change "name" column to "type"

- src/Cashier.php
This PR uses the Laravel container to resolve `StripeClient` instead of initializing it in the Cashier class.
In complex test scenarios, this would allow us to mock the StripeClient instead of sending actual requests to Stripe and make those test cases focus only on actual business logic.
> [14.x] Use container to resolve `StripeClient`
