src/Laravel/Cashier/CashierServiceProvider.php

Added the possibility to use vendor:publish to publish the views (currently only one: receipt.blade.php).

[Proposal] Publish views

---

src/Laravel/Cashier/WebhookController.php

As discussed in closed PR https://github.com/laravel/cashier/pull/150
There is corresponding doc changes here as well: https://github.com/laravel/docs/pull/1277

[Proposal] Change cancellation webhook to correct hook from Stripe API

---

composer.json
src/Laravel/Cashier/Customer.php
src/Laravel/Cashier/Invoice.php
src/Laravel/Cashier/StripeGateway.php
src/Laravel/Cashier/WebhookController.php

Reopening on the `master` branch. Refer to the prior pull request for details: https://github.com/laravel/cashier/pull/152

Updating to stripe/stripe-php=~2.0

---

src/Laravel/Cashier/WebhookController.php

Revert "Fixing an issue with not being able to test stripe webhooks"

---

src/Laravel/Cashier/WebhookController.php

please see edits.
fixes cancellation problem when you cancel at end of billing period and then cancel it immediately.
fixes trial period bug

fixes two bugs

---

src/Laravel/Cashier/StripeGateway.php
tests/StripeGatewayTest.php

Here's the commit on 5.0.
See https://github.com/laravel/cashier/pull/209
Thanks!

billing_cycle_anchor Support (on 5.0 branch)

---

src/Laravel/Cashier/WebhookController.php

Condition operator "And" should be : && instead of &

Typo in userIsSubscribedWithoutACard()

---

src/Laravel/Cashier/Billable.php
tests/BillableTraitTest.php

added missing storagePath option for invoiceFile / invoiceDownload in Billable trait.
Update unit tests

added missing storagePath option

---

src/Invoice.php
src/Subscription.php

Avoid FQN in code
Also fix a docblock

[6.0] Avoid FQN in code

---

.editorconfig
.gitattributes

[6.0] Add some dotfiles

---

src/Billable.php

[6.0] Import missing exception

---

src/Http/Controllers/WebhookController.php

[6.0] Fix docblock

---

src/Subscription.php

Fixed minor typo's in _src/Subscription.php_.

Fixed typo's in Subscription.php

---

src/Billable.php

Fix for https://github.com/laravel/cashier/issues/270 - attempting to update card with a null token

Fix newSubscription with null tokens

---

src/Billable.php

Fix spelling in comment

---

src/Billable.php

Some code cleanup on Billable trait. Remove unnecessary else statement.

Cleanup code structure on Billable trait.

---

readme.md

Adds info for setting up tests locally

Adds info to readme for testing

---

src/Billable.php
src/Cashier.php
src/Subscription.php
tests/CashierTest.php

Refunds invoices

---

src/Billable.php

Add invoiceForUpcoming method to create invoice items without immediately paying them.
See proposal https://github.com/laravel/cashier/issues/335.

Add invoiceForUpcoming method

---

src/SubscriptionBuilder.php

Fix phpdoc

---

src/Billable.php
src/Card.php

This PR adds the following methods:
```
// Get a collection of customer cards.
$user->cards();
// Delete all customer cards.
$user->deleteCard();
```

add get all cards and delete card

---

composer.json

This is related to #352. I have verified that unit tests pass by making this change. This will, at the time of this PR, install Stripe v4.3.0.

Upgraded to Stripe v4

---

src/SubscriptionBuilder.php

This pull request mirrors the fixes applied to the 7.0 branch via pull request #350.

Fix coupon being double applied

---

src/CashierServiceProvider.php

This contribution follows on the work I began in laravel/framework, here:
laravel/framework#18506
Thank you for your consideration.

Make consistent the disuse of helper functions within ServiceProviders

---

composer.json
tests/CashierTest.php
tests/Fixtures/CashierTestControllerStub.php
tests/Fixtures/User.php
tests/Fixtures/WebhookControllerTestStub.php
tests/WebhookControllerTest.php

[7.0] Use PSR-4 for tests.

---

src/Billable.php
src/Cashier.php
src/Http/Controllers/WebhookController.php
src/Invoice.php
src/Subscription.php

[7.0] Fix all docblocks

---

composer.json

[7.0] Some composer adjustments.

---

src/Billable.php

Follow up pull request for #450.

Feature introduce get default card

---

src/Subscription.php

Game changer: Added return type to the docblock

[7.0] add return type to doc block

---

resources/views/receipt.blade.php

This PR updates the receipt template to use the null coalesce operator.

convert 'or' usage to '??'

---

src/Http/Middleware/VerifyWebhookSignature.php
tests/VerifyWebhookSignatureTest.php

Build was failing because of the helper methods. Using DI to inject mocks resolves this.

[7.0] Fix tests for VerifyWebhookSignature

---

src/Billable.php

Was failing on the 7.0 branch.

[7.0] Fix StyleCI failures

---

.travis.yml
composer.json
phpunit.xml
readme.md
resources/views/receipt.blade.php
src/Billable.php
src/Cashier.php
src/Http/Controllers/WebhookController.php
src/Http/Middleware/VerifyWebhookSignature.php
src/Subscription.php
src/SubscriptionBuilder.php
tests/CashierTest.php
tests/VerifyWebhookSignatureTest.php

All the changes from 7.0 that are missing on master at the moment.

[8.0] Merge 7.0 changes

---

.travis.yml

Keeps things consistent with the other repos and should speed things up.

[8.0] Disable xdebug

---

readme.md
tests/CashierTest.php
tests/TestCase.php

Another attempt at #622, this time supporting concurrency. I ran two tests at once without any problems.

Bootstrap stripe tests

---

tests/Unit/VerifyWebhookSignatureTest.php
tests/Unit/WebhookControllerTest.php

Cleans up the unit test suite making the tests more readable and logical.

[10.0] Cleanup unit tests

---

src/Billable.php
src/SubscriptionBuilder.php

Moved this to the Billable trait because it makes more sense and we'll be able to re-use this functionality in other places. Couldn't figure out a better name for this.

[10.0] Move create or get customer to Billable trait

---

resources/views/payment.blade.php

Refactor payment page with Vue.js

[10.0] Payment page refactor

---

src/Subscription.php

This parameter on the `updateQuantity` is never used.

[10.0] Remove unused parameter

---

resources/views/payment.blade.php

A label with an incorrect for attribute

---

src/Billable.php

[10.0] Allow hasCompletePayment() to check other subscriptions than “default”.

---

CHANGELOG.md
UPGRADE.md

This updates the upgrade guide for the upcoming v10 release.

[10.0] Update UPGRADE.md

---

UPGRADE.md

I forgot to document these methods which were moved to the config file.

[10.0] Document removed methods

---

.travis.yml
composer.json
tests/Integration/IntegrationTestCase.php
tests/Integration/SubscriptionsTest.php
tests/Integration/WebhooksTest.php
tests/Unit/InvoiceTest.php
tests/Unit/VerifyWebhookSignatureTest.php

This makes sure Cashier will build for Laravel 6

[10.0] Fix 6.0 build

---

src/Payment.php
src/Subscription.php

Use constants for statuses

---

src/Billable.php
tests/Unit/CustomerTest.php

Closes https://github.com/laravel/cashier/issues/833

[10.x] Assert customer exists before retrieving

---

UPGRADE.md

Documentation URL was localized for Belgium. It's fixed now.

Localized stripe URL fixed

---

src/Invoice.php
src/InvoiceItem.php
src/PaymentMethod.php

Closes https://github.com/laravel/cashier/issues/839

[10.x] Add getters for owner instances to objects

---

src/Cashier.php

Allow to pass in a custom locale when formatting amounts. 
Closes https://github.com/laravel/cashier/issues/780

[11.x] Custom locale

---

src/SubscriptionBuilder.php

Updates the `add` method with the same changes that were already done for the `create` method.

[11.x] Update add method

---

src/Subscription.php
src/SubscriptionItem.php

See https://github.com/laravel/cashier/issues/936

[11.x] Add convenience methods to update stripe objects

---

src/Subscription.php
src/SubscriptionBuilder.php
tests/Feature/SubscriptionsTest.php

Fixes https://github.com/laravel/cashier/issues/958

[12.x] Fix validating payment intent

---

composer.json
src/Concerns/InteractsWithPaymentBehavior.php
src/Http/Controllers/WebhookController.php
src/Subscription.php
tests/Feature/MultiplanSubscriptionsTest.php
tests/Feature/SubscriptionsTest.php
tests/Feature/WebhooksTest.php
tests/Unit/PaymentTest.php
tests/Unit/SubscriptionTest.php

[12.x] Replace hardcoded strings with constants

---

src/Concerns/ManagesSubscriptions.php

Fixes https://github.com/laravel/cashier-stripe/issues/1008

[12.x] Fix n+1 problem with subscription retrieval

---

src/Concerns/ManagesSubscriptions.php
tests/Feature/SubscriptionsTest.php
tests/Unit/CustomerTest.php

Equivalent of https://github.com/laravel/cashier-paddle/pull/87

[12.x] Fix trial ends at check

---

src/SubscriptionBuilder.php
tests/Feature/CheckoutTest.php

Fixes https://github.com/laravel/cashier-stripe/issues/1049

[12.x] Fix tax rates for subscription checkouts

---

src/Payment.php

Adds a small convenience method for people using "hold & capture later" feature from Stripe.
https://stripe.com/docs/payments/capture-later

[12.x] Add capture method

---

src/Concerns/ManagesCustomer.php

This PR adds a new parameter to the billing portal methods so people can pass in extra arguments if they need to.

[13.x] billing portal arguments

---

src/Subscription.php

Fixes https://github.com/laravel/cashier-stripe/issues/1112

[12.x] Fix latest_invoice retrieval

---

src/Checkout.php
src/Invoice.php
src/InvoiceLineItem.php
src/Payment.php
src/PaymentMethod.php

This will allow all internal Cashier Stripe classes to be easily serialized when, for example, returned from a route.

[12.x] Implement object serialization

---

src/Invoice.php
tests/Unit/InvoiceTest.php

Fixes https://github.com/laravel/cashier-stripe/issues/1143

[12.x] Fix discount calculation

---

src/SubscriptionBuilder.php
tests/Feature/CheckoutTest.php
tests/Feature/InvoicesTest.php

Alternative to https://github.com/laravel/cashier-stripe/pull/1164
Fixes https://github.com/laravel/cashier-stripe/issues/1163

[12.x] Fix coupons with Stripe Checkout sessions

---

UPGRADE.md

[13.x] v13 Upgrade guide

---

src/Subscription.php
tests/Feature/MeteredBillingTest.php

Replacement for https://github.com/laravel/cashier-stripe/pull/1188
Fixes #1187

[13.x] Fix adding metered plan to subscription

---

src/Concerns/PerformsCharges.php
src/SubscriptionBuilder.php

Fixes https://github.com/laravel/cashier-stripe/issues/1208

[13.x] Fix collecting tax ids

---

src/Invoice.php

Fixes typo

---

src/Subscription.php

[13.x] Allow promo codes on subscription updates

---

src/Checkout.php
src/Invoice.php
src/Payment.php
src/PaymentMethod.php

Add ReturnTypeWillChange to PaymentMethod

---

src/SubscriptionBuilder.php

Instead of automatically collecting payments through recurring payments, invoices will be sent to the customer.

[13.x] Add createAndSendInvoice method

---

src/Subscription.php

Small tweak to simplify a cancelation check.

[13.x] Simplify cancelation check

---

src/Invoice.php
tests/Unit/InvoiceTest.php

This fixes an issue where no tax is applied on an invoice.

Fix issue with zero tax on invoice

---

src/Invoice.php

We can use the owner of the invoice for this, instead of the Cashier class.

[13.x] Update reference to Stripe SDK

---

src/Console/WebhookCommand.php

This fixes an issue where a resource is used directly to perform an update rather than the service which is the preferred way of doing things.

[13.x] Fix webhook command

---

src/Invoice.php

[12.x] Fix tax on invoice

---

src/Concerns/HandlesTaxes.php
src/Concerns/ManagesPaymentMethods.php
src/Payment.php
src/Subscription.php

This PR removes some functionality that was deprecated in previous Cashier versions.

[14.x] Remove deprecated functionality

---

.github/workflows/tests.yml
composer.json

Drops MoneyPHP 3.x support for Cashier v14

[14.x] Drop MoneyPHP 3.x

---

src/Concerns/ManagesCustomer.php

While working on the Spark balances feature I noticed it's not very clear that you need to apply a negative amount to increase a customer's balance. I hope to make this more easier for developers by adding these readable 
methods.

Add new balance transaction methods

---

src/Subscription.php
src/SubscriptionBuilder.php
tests/Feature/MeteredBillingTest.php
tests/Feature/SubscriptionsWithMultiplePricesTest.php

Adjust multiprice wording

---

src/Concerns/PerformsCharges.php

Just a super minor change here. Fixed a typo for an internal error message.

fix minor typo

---

UPGRADE.md

This PR fixes a typo in the upgrade guide

Fix typo in upgrade guide

---

src/Concerns/ManagesInvoices.php

This PR allows to pass pay options to the `pay` method when creating invoices.
Alternative and better DX than https://github.com/laravel/cashier-stripe/pull/1459.

[14.x] Pass pay options to pay method

---

database/migrations/2019_05_03_000002_create_subscriptions_table.php
database/migrations/2019_05_03_000003_create_subscription_items_table.php

[14.x] Modernize migrations

---

src/InvoiceLineItem.php

Reverts laravel/cashier-stripe#1475

Revert "Exception Attempt to read property "percentage" on string"

---

database/factories/SubscriptionFactory.php
database/factories/SubscriptionItemFactory.php
database/migrations/2019_05_03_000001_create_customer_columns.php
database/migrations/2019_05_03_000002_create_subscriptions_table.php
database/migrations/2019_05_03_000003_create_subscription_items_table.php

Please check https://github.com/laravel/laravel/pull/6010 for details about this pull request.

[14.x] Adds types to database migrations and factories

---

.gitattributes
.github/workflows/static-analysis.yml
composer.json
phpstan.neon.dist

This pull request adds type checking to this repository.

[14.x] Adds type checking

---

src/Concerns/ManagesCustomer.php

https://github.com/laravel/cashier-stripe/issues/1546

Update ManagesCustomer.php > createOrGetStripeCustomer() > allow "expand" when retrieving a Customer

---

src/Http/Controllers/WebhookController.php
src/Subscription.php

This will be a much more reliable cleanup of subscription items which aren't attached to a subscription anymore.

[14.x] Better cleanup for subscription items

---

src/Cashier.php

Fixes https://github.com/laravel/cashier-stripe/issues/1598

[14.x] Fix soft deleted customers

---

.github/CONTRIBUTING.md

Add note about test rate limiting

---

UPGRADE.md

v15 upgrade guide

---

.github/workflows/tests.yml
composer.json
phpunit.xml.dist
src/CashierServiceProvider.php

This pull request adds Laravel 11 support to Cashier Stripe.

[develop] Adds Laravel 11 support
